#!/usr/bin/env python3
"""Register the replaceable-cognitive-substrates chapter and its source intake.

The integration is idempotent. It records external papers as comparators and
the author-supplied ChatGPT shares as design-intent inputs. Nothing in this
script promotes the chapter above argument or records a local reproduction.
"""
from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ROOT / "sources/source_inventory.json"
STRUCTURE = ROOT / "book_structure.json"
CHAPTER_ID = "replaceable-cognitive-substrates-beyond-transformer-monoculture"


NEW_RECORDS = [
    {
        "id": "corben_chatgpt_kiss_irreducible_intelligence_2026",
        "title": "KISS versus Irreducible Intelligence (author-supplied design conversation)",
        "priority": "supporting",
        "layer": "author_intent_replaceable_cognitive_substrates",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://chatgpt.com/share/6a57604d-59b4-83ea-8da7-b9d3d52658f8",
        "notes": "Corben-supplied design conversation for search-verify-compile, exact-latent separation, a compact recursive kernel, and total-system KISS accounting. Author intent only; not independent evidence or a reproduced architecture.",
        "source_type": "author_supplied_conversation",
        "published": "2026-07-15",
        "citation_label": "Sorenson and ChatGPT (2026), KISS versus Irreducible Intelligence",
    },
    {
        "id": "corben_chatgpt_onecell_theseus_2026",
        "title": "OneCell and Theseus Architecture Handoff (author-supplied design conversation)",
        "priority": "supporting",
        "layer": "author_intent_onecell_and_architectural_rsi",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://chatgpt.com/share/6a57781e-17a4-83ea-aaae-fa263a9ac2fd",
        "notes": "Corben-supplied design conversation for a Cognitive Kernel ABI, typed state lanes, inner recurrence, outer exact search, verified abstraction, and Theseus-governed architecture tournaments. Author intent only; OneCell remains an unimplemented falsifiable candidate.",
        "source_type": "author_supplied_conversation",
        "published": "2026-07-15",
        "citation_label": "Sorenson and ChatGPT (2026), OneCell and Theseus Architecture Handoff",
    },
    {
        "id": "ext_attention_is_all_you_need_2017",
        "title": "Attention Is All You Need",
        "priority": "external_literature",
        "layer": "dense_attention_sequence_substrate",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/1706.03762",
        "notes": "Primary Transformer paper and dense-attention baseline. It supports the historical architecture and parallel sequence-processing comparison, not a claim that Transformers are universally optimal or locally reproduced.",
        "source_type": "conference_paper",
        "arxiv_id": "1706.03762",
        "published": "2017-06-12",
        "citation_label": "Vaswani et al. (2017), Attention Is All You Need",
        "doi": "10.48550/arXiv.1706.03762",
    },
    {
        "id": "ext_mamba2_ssd_2024",
        "title": "Transformers are SSMs: Generalized Models and Efficient Algorithms Through Structured State Space Duality",
        "priority": "external_literature",
        "layer": "state_space_duality_and_sequence_substrates",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2405.21060",
        "notes": "Primary Mamba-2/structured-state-space-duality comparator connecting SSM and attention-like formulations. No local model, kernel, quality, scaling, or hardware result is reproduced.",
        "source_type": "conference_paper",
        "arxiv_id": "2405.21060",
        "published": "2024-05-31",
        "citation_label": "Dao and Gu (2024), Transformers are SSMs",
        "doi": "10.48550/arXiv.2405.21060",
    },
    {
        "id": "ext_s4_2022",
        "title": "Efficiently Modeling Long Sequences with Structured State Spaces",
        "priority": "external_literature",
        "layer": "structured_state_space_sequence_substrates",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2111.00396",
        "notes": "Foundational S4 comparator for structured state-space sequence models, efficient long-range computation, and the lineage that precedes selective SSMs. Source-reported benchmark and generation results are not reproduced and do not establish exact recall or governed substitutability.",
        "source_type": "conference_paper",
        "arxiv_id": "2111.00396",
        "published": "2021-10-31",
        "citation_label": "Gu, Goel, and Re (2022), Structured State Spaces",
        "doi": "10.48550/arXiv.2111.00396",
    },
    {
        "id": "ext_mamba3_2026",
        "title": "Mamba-3: Improved Sequence Modeling using State Space Principles",
        "priority": "external_literature",
        "layer": "modern_selective_state_space_sequence_substrates",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2603.15569",
        "notes": "Current 2026 selective-SSM comparator for complex-valued state updates, discretization, and multi-input/multi-output formulation. Recent source-reported results are not locally reproduced and must not set the chapter conclusion by recency.",
        "source_type": "preprint",
        "arxiv_id": "2603.15569",
        "published": "2026-03-16",
        "citation_label": "Lahoti et al. (2026), Mamba-3",
        "doi": "10.48550/arXiv.2603.15569",
    },
    {
        "id": "ext_hyperscale_lottery_2026",
        "title": "The Hyperscale Lottery: How State-Space Models Have Sacrificed Edge Efficiency",
        "priority": "external_literature",
        "layer": "hardware_specific_state_space_efficiency_counterevidence",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2604.07935",
        "notes": "Current edge-hardware counterstudy measuring Mamba-family latency outside hyperscale-GPU conditions. Its source-reported results require platform-stratified latency, memory, and energy accounting; they are not locally reproduced and do not settle the quality-efficiency frontier.",
        "source_type": "preprint",
        "arxiv_id": "2604.07935",
        "published": "2026-04-09",
        "citation_label": "Geens et al. (2026), The Hyperscale Lottery",
        "doi": "10.48550/arXiv.2604.07935",
    },
    {
        "id": "ext_gated_deltanet_2024",
        "title": "Gated Delta Networks: Improving Mamba2 with Delta Rule",
        "priority": "external_literature",
        "layer": "linear_attention_and_adaptive_memory",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2412.06464",
        "notes": "Primary gated-delta-rule comparator for targeted recurrent-memory updates, rapid erasure, parallel training, and hybrid attention/SSM compositions. Source-reported retrieval, extrapolation, efficiency, and quality results are not locally reproduced.",
        "source_type": "preprint",
        "arxiv_id": "2412.06464",
        "published": "2024-12-09",
        "citation_label": "Yang et al. (2024), Gated Delta Networks",
        "doi": "10.48550/arXiv.2412.06464",
    },
    {
        "id": "ext_jamba_2024",
        "title": "Jamba: A Hybrid Transformer-Mamba Language Model",
        "priority": "external_literature",
        "layer": "hybrid_attention_state_space_mixture_of_experts",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2403.19887",
        "notes": "Primary large-scale hybrid Transformer-Mamba-MoE comparator. It motivates route- and composition-aware accounting; its reported quality, context, throughput, and memory results are not locally reproduced and do not establish that the specific mixture is generally optimal.",
        "source_type": "preprint",
        "arxiv_id": "2403.19887",
        "published": "2024-03-28",
        "citation_label": "Lieber et al. (2024), Jamba",
        "doi": "10.48550/arXiv.2403.19887",
    },
    {
        "id": "ext_neural_message_passing_2017",
        "title": "Neural Message Passing for Quantum Chemistry",
        "priority": "external_literature",
        "layer": "graph_relational_message_passing",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/1704.01212",
        "notes": "Primary message-passing neural-network framework for learned computation over graph structure. Its molecular results motivate a non-token-native relational lane but do not establish general reasoning, dynamic graph memory, exact state, or local reproduction.",
        "source_type": "conference_paper",
        "arxiv_id": "1704.01212",
        "published": "2017-04-04",
        "citation_label": "Gilmer et al. (2017), Neural Message Passing for Quantum Chemistry",
        "doi": "10.48550/arXiv.1704.01212",
    },
    {
        "id": "ext_hyena_hierarchy_2023",
        "title": "Hyena Hierarchy: Towards Larger Convolutional Language Models",
        "priority": "external_literature",
        "layer": "long_convolution_sequence_substrates",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2302.10866",
        "notes": "Primary long-convolution comparator for subquadratic sequence mixing and hardware-aware architecture comparisons. No local training, throughput, quality, recall, or scaling result is reproduced.",
        "source_type": "conference_paper",
        "arxiv_id": "2302.10866",
        "published": "2023-02-21",
        "citation_label": "Poli et al. (2023), Hyena Hierarchy",
        "doi": "10.48550/arXiv.2302.10866",
    },
    {
        "id": "ext_rwkv_2023",
        "title": "RWKV: Reinventing RNNs for the Transformer Era",
        "priority": "external_literature",
        "layer": "linear_recurrent_language_models",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://aclanthology.org/2023.findings-emnlp.936/",
        "notes": "Primary recurrent language-model comparator combining parallelizable training with recurrent inference. Reported benchmark, memory, and inference properties are not reproduced locally.",
        "source_type": "conference_paper",
        "published": "2023-12-01",
        "citation_label": "Peng et al. (2023), RWKV",
        "doi": "10.18653/v1/2023.findings-emnlp.936",
    },
    {
        "id": "ext_xlstm_2024",
        "title": "xLSTM: Extended Long Short-Term Memory",
        "priority": "external_literature",
        "layer": "modern_gated_recurrent_sequence_substrates",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2405.04517",
        "notes": "Primary modern-LSTM comparator for revised gating, memory, and scalable recurrent language modeling. No xLSTM training, scaling, quality, or inference result is reproduced locally.",
        "source_type": "conference_paper",
        "arxiv_id": "2405.04517",
        "published": "2024-05-07",
        "citation_label": "Beck et al. (2024), xLSTM",
        "doi": "10.48550/arXiv.2405.04517",
    },
    {
        "id": "ext_ttt_layers_2024",
        "title": "Learning to (Learn at Test Time): RNNs with Expressive Hidden States",
        "priority": "external_literature",
        "layer": "test_time_learned_state_sequence_substrates",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2407.04620",
        "notes": "Primary test-time-training-layer comparator that treats hidden state as a learned model updated on the sequence. It motivates explicit online-state custody and rollback; no local quality or efficiency result is reproduced.",
        "source_type": "conference_paper",
        "arxiv_id": "2407.04620",
        "published": "2024-07-05",
        "citation_label": "Sun et al. (2024), Learning to Learn at Test Time",
        "doi": "10.48550/arXiv.2407.04620",
    },
    {
        "id": "ext_titans_2025",
        "title": "Titans: Learning to Memorize at Test Time",
        "priority": "external_literature",
        "layer": "test_time_neural_long_term_memory",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2501.00663",
        "notes": "Primary neural-memory comparator for test-time memorization and long-context sequence modeling. The paper motivates mutable-state provenance and rollback tests; no local model or benchmark result is reproduced.",
        "source_type": "preprint",
        "arxiv_id": "2501.00663",
        "published": "2025-01-01",
        "citation_label": "Behrouz et al. (2025), Titans",
        "doi": "10.48550/arXiv.2501.00663",
    },
    {
        "id": "ext_kan_2024",
        "title": "KAN: Kolmogorov-Arnold Networks",
        "priority": "external_literature",
        "layer": "learned_univariate_function_networks",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2404.19756",
        "notes": "Primary KAN proposal replacing fixed node activations/linear edge weights with learned univariate edge functions. Interpretability and scientific-task demonstrations are source-reported and do not establish a general MLP or Transformer replacement.",
        "source_type": "conference_paper",
        "arxiv_id": "2404.19756",
        "published": "2024-04-30",
        "citation_label": "Liu et al. (2024), KAN",
        "doi": "10.48550/arXiv.2404.19756",
    },
    {
        "id": "ext_kan_or_mlp_fairer_comparison_2024",
        "title": "KAN or MLP: A Fairer Comparison",
        "priority": "external_literature",
        "layer": "architecture_comparison_methodology",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2407.16674",
        "notes": "Critical matched-comparison source for KAN versus MLP under parameter, FLOP, and task controls. It is included to prevent architecture enthusiasm from substituting for fair accounting; no local comparison is reproduced.",
        "source_type": "preprint",
        "arxiv_id": "2407.16674",
        "published": "2024-07-23",
        "citation_label": "Yu et al. (2024), KAN or MLP",
        "doi": "10.48550/arXiv.2407.16674",
    },
    {
        "id": "ext_neural_turing_machines_2014",
        "title": "Neural Turing Machines",
        "priority": "external_literature",
        "layer": "differentiable_external_memory",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/1410.5401",
        "notes": "Primary differentiable-controller/external-memory source. It motivates variable-size memory interfaces and out-of-distribution algorithmic tests; toy-task results do not establish reliable exact memory or general computation.",
        "source_type": "preprint",
        "arxiv_id": "1410.5401",
        "published": "2014-10-20",
        "citation_label": "Graves, Wayne, and Danihelka (2014), Neural Turing Machines",
        "doi": "10.48550/arXiv.1410.5401",
    },
    {
        "id": "ext_differentiable_neural_computer_2016",
        "title": "Hybrid computing using a neural network with dynamic external memory",
        "priority": "external_literature",
        "layer": "differentiable_external_memory",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://doi.org/10.1038/nature20101",
        "notes": "Primary Differentiable Neural Computer source for learned controllers over dynamic external memory. Source-reported graph and reasoning tasks do not establish reliable exact state, scalable memory, or local reproduction.",
        "source_type": "journal_article",
        "published": "2016-10-12",
        "citation_label": "Graves et al. (2016), Differentiable Neural Computer",
        "doi": "10.1038/nature20101",
    },
    {
        "id": "ext_liquid_time_constant_networks_2021",
        "title": "Liquid Time-constant Networks",
        "priority": "external_literature",
        "layer": "continuous_time_neural_dynamics",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://doi.org/10.1609/aaai.v35i9.16936",
        "notes": "Primary continuous-time recurrent architecture source for input-dependent time constants and dynamical-system behavior. Reported time-series results and stability analysis do not establish broad cognitive superiority or a local implementation.",
        "source_type": "conference_paper",
        "published": "2021-05-18",
        "citation_label": "Hasani et al. (2021), Liquid Time-constant Networks",
        "doi": "10.1609/aaai.v35i9.16936",
    },
    {
        "id": "ext_tiny_recursive_model_2025",
        "title": "Less is More: Recursive Reasoning with Tiny Networks",
        "priority": "external_literature",
        "layer": "tiny_weight_tied_recursive_reasoning",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2510.04871",
        "notes": "Primary Tiny Recursive Model proposal and narrow puzzle-domain result. It motivates a compact weight-tied OneCell comparator but does not establish general reasoning, language capability, deep effective recursion, or total-system simplicity.",
        "source_type": "preprint",
        "arxiv_id": "2510.04871",
        "published": "2025-10-06",
        "citation_label": "Jolicoeur-Martineau (2025), Less is More",
        "doi": "10.48550/arXiv.2510.04871",
    },
    {
        "id": "ext_trm_arc_agi_analysis_2025",
        "title": "Tiny Recursive Models on ARC-AGI-1: Inductive Biases, Identity Conditioning, and Test-Time Compute",
        "priority": "external_literature",
        "layer": "recursive_model_critical_evaluation",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2512.11847",
        "notes": "Critical TRM analysis reporting material dependence on 1000-sample voting, puzzle identity, and shallow effective recursion. It is a source-reported audit rather than a local reproduction and sets preregistered identity, sampling, and recursion-depth controls.",
        "source_type": "preprint",
        "arxiv_id": "2512.11847",
        "published": "2025-12-04",
        "citation_label": "Roye-Azar et al. (2025), Tiny Recursive Models on ARC-AGI-1",
        "doi": "10.48550/arXiv.2512.11847",
    },
    {
        "id": "ext_tiny_autoregressive_recursive_models_2026",
        "title": "Tiny Autoregressive Recursive Models",
        "priority": "external_literature",
        "layer": "recursive_model_controlled_ablation",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2603.08082",
        "notes": "Controlled compute-matched study that progressively transforms a standard autoregressive model into a TRM-like system and reports no reliable advantage from the full autoregressive TRM mechanism. It motivates mechanism-level rather than label-level ablation.",
        "source_type": "workshop_paper",
        "arxiv_id": "2603.08082",
        "published": "2026-03-09",
        "citation_label": "Rauba, Fanconi, and van der Schaar (2026), Tiny Autoregressive Recursive Models",
        "doi": "10.48550/arXiv.2603.08082",
    },
    {
        "id": "ext_unimatrix_2026",
        "title": "Associative-State Universal Transformers: Sparse Retrieval Meets Structured Recurrence",
        "priority": "external_literature",
        "layer": "structured_recurrence_and_sparse_retrieval",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2604.25930",
        "notes": "Current UniMatrix preprint whose negative associative-recall result shows compressed recurrent state alone is insufficient in its setup, while explicit sparse slots and pointer-level routing materially change the result. No local reproduction or general conclusion follows.",
        "source_type": "preprint",
        "arxiv_id": "2604.25930",
        "published": "2026-04-01",
        "citation_label": "Xiao (2026), Associative-State Universal Transformers",
        "doi": "10.48550/arXiv.2604.25930",
    },
    {
        "id": "ext_memory_caching_2026",
        "title": "Memory Caching: RNNs with Growing Memory",
        "priority": "external_literature",
        "layer": "growing_recurrent_memory",
        "chapter_targets": [CHAPTER_ID],
        "url": "https://arxiv.org/abs/2602.24281",
        "notes": "Current recurrent-memory comparator that caches hidden-state checkpoints and exposes a trade between fixed recurrent memory and growing addressable memory. Its source-reported recall results still leave the Transformer strongest on the reported in-context recall tasks.",
        "source_type": "preprint",
        "arxiv_id": "2602.24281",
        "published": "2026-02-27",
        "citation_label": "Behrouz et al. (2026), Memory Caching",
        "doi": "10.48550/arXiv.2602.24281",
    },
]


EXISTING_SOURCE_IDS = [
    "scf",
    "rmi",
    "benchmaxxing",
    "ext_mamba_2023",
    "ext_retnet_2023",
    "ext_universal_transformer_2019",
    "ext_dynamic_compute_recurrent_transformers_2026",
    "ext_dreamcoder_2020",
]


def mapping(source_id: str, support: str, limits: str, refs: list[str]) -> dict:
    return {
        "source_id": source_id,
        "mapped_support": support,
        "limits": limits,
        "passage_refs": refs,
        "passage_review_note": "Primary source or author-supplied design input was reviewed for this bounded contribution and its limits. No local implementation, reproduction, superiority, safety, deployment, or support-state movement is inferred.",
        "passage_review_state": "reviewed",
    }


SOURCE_MAPPINGS = [
    mapping("corben_chatgpt_kiss_irreducible_intelligence_2026", "Supplies the search-verify-compile ratchet, exact-latent split, frozen-core question, and total-system KISS accounting as author intent.", "A design conversation is not independent evidence; all proposed mechanisms remain hypotheses.", ["public share: KISS versus Irreducible Intelligence, reviewed 2026-07-15"]),
    mapping("corben_chatgpt_onecell_theseus_2026", "Supplies OneCell, typed state lanes, the Cognitive Kernel ABI, inner recurrence plus outer exact search, and a governed Theseus tournament as author intent.", "OneCell is neither implemented nor selected; the conversation cannot support performance or generality claims.", ["public share: OneCell and Theseus Architecture Handoff, reviewed 2026-07-15"]),
    mapping("scf", "Supplies stable capability identity, replaceable implementation, qualification, lifecycle, fallback, and rollback contracts above a changing cognitive kernel.", "SCF is a local design source, not evidence that heterogeneous learned substrates are interchangeable or safe.", ["sources/raw/google_docs/scf.txt:40-64", "sources/raw/google_docs/scf.txt:279-315", "sources/raw/google_docs/scf.txt:844-895"]),
    mapping("rmi", "Supplies modular routing, specialist lifecycle, residual retention, and bounded authority for substrate-neutral route selection.", "No learned architecture tournament or cognitive-kernel ABI is implemented by this source.", ["sources/raw/google_docs/rmi.txt:25-45", "sources/raw/google_docs/rmi.txt:268-304", "sources/raw/google_docs/rmi.txt:608-640"]),
    mapping("benchmaxxing", "Supplies benchmark ratchets, held-outs, anti-Goodhart controls, wall diagnosis, regression retention, and architecture-change criteria.", "It does not show that any candidate architecture wins a matched comparison.", ["sources/raw/google_docs/benchmaxxing.txt:269-335", "sources/raw/google_docs/benchmaxxing.txt:491-630"]),
    mapping("ext_attention_is_all_you_need_2017", "Defines the dense self-attention Transformer baseline and its training-parallel sequence-processing design.", "The paper is a baseline, not proof of universal optimality or a local reproduction.", ["arXiv:1706.03762, Abstract and Sections 1-3"]),
    mapping("ext_mamba_2023", "Introduces selective state spaces and hardware-aware recurrent computation as a non-attention sequence substrate.", "Reported scaling and benchmark results are not reproduced and do not establish governed replaceability.", ["arXiv:2312.00752, Abstract and Sections 1-3"]),
    mapping("ext_mamba2_ssd_2024", "Connects structured state spaces and attention-like formulations through state-space duality and efficient algorithms.", "Formal duality and source benchmarks do not erase state, kernel, or hardware differences.", ["arXiv:2405.21060, Abstract and Sections 2-4"]),
    mapping("ext_s4_2022", "Provides the foundational structured-state-space sequence model and long-range benchmark lineage preceding selective SSMs.", "Source-reported long-range and generation results do not establish exact retrieval, general cognition, or governed replacement.", ["arXiv:2111.00396, Abstract and Sections 1-3"]),
    mapping("ext_mamba3_2026", "Adds a current selective-SSM comparator with revised state update, discretization, and MIMO design.", "Its recency and source-reported results do not make it the preferred substrate.", ["arXiv:2603.15569, Abstract and architecture sections"]),
    mapping("ext_hyperscale_lottery_2026", "Supplies adversarial edge-hardware measurements showing that an architecture optimized for hyperscale GPU utilization can move cost onto smaller deployment targets.", "One preprint and its selected devices do not establish a universal edge penalty or outweigh model quality; the result sets a platform-stratified measurement requirement.", ["arXiv:2604.07935, Abstract and latency evaluation"]),
    mapping("ext_gated_deltanet_2024", "Adds targeted delta-rule memory updates, gating, and hybrid linear-attention/state-space comparisons.", "Source-reported retrieval and efficiency gains do not establish exact memory, governed state, or local superiority.", ["arXiv:2412.06464, Abstract and architecture/evaluation sections"]),
    mapping("ext_jamba_2024", "Provides a large-scale Transformer-Mamba-MoE hybrid comparator and evidence that architecture composition itself is a design variable.", "Its source-reported results do not establish that the mixture is generally optimal or that ABI routing and lifecycle costs are negligible.", ["arXiv:2403.19887, Abstract and architecture sections"]),
    mapping("ext_neural_message_passing_2017", "Provides a learned message-passing framework over graph-structured inputs as a non-token-native relational substrate comparator.", "Molecular prediction results do not establish general cognition, exact graph memory, dynamic routing, or local reproduction.", ["arXiv:1704.01212, Abstract and Sections 1-3"]),
    mapping("ext_retnet_2023", "Provides parallel, recurrent, and chunkwise recurrent computation modes at the attention-recurrence boundary.", "Reported efficiency and quality are not reproduced and do not prove exact state tracking.", ["arXiv:2307.08621, Abstract and Sections 1-3"]),
    mapping("ext_rwkv_2023", "Provides a recurrent language-model baseline with parallelizable training and recurrent inference.", "Reported benchmark and memory properties remain source results.", ["ACL Anthology 2023.findings-emnlp.936, Abstract and model sections"]),
    mapping("ext_hyena_hierarchy_2023", "Provides a long-convolution alternative and hardware-aware subquadratic sequence-mixing comparison.", "No local throughput, quality, recall, or scaling claim follows.", ["arXiv:2302.10866, Abstract and Sections 1-3"]),
    mapping("ext_xlstm_2024", "Provides a modern gated recurrent baseline for memory and scalable sequence modeling.", "No local training, depth-extrapolation, quality, or efficiency result exists.", ["arXiv:2405.04517, Abstract and architecture sections"]),
    mapping("ext_universal_transformer_2019", "Provides shared-weight depth recurrence and adaptive computation as a bridge between fixed-depth Transformers and iterative kernels.", "Expressivity and benchmark reports do not establish stable indefinite recurrence or useful stopping.", ["arXiv:1807.03819, Abstract and Sections 2-4"]),
    mapping("ext_dynamic_compute_recurrent_transformers_2026", "Provides current evidence and evaluation pressure for learned dynamic compute allocation in recurrent Transformers.", "Source results do not validate the chapter's router, recurrence, or stopping rules.", ["arXiv:2602.08864, Abstract and evaluation sections"]),
    mapping("ext_ttt_layers_2024", "Treats hidden state as a learned model updated at test time, expanding the state and rollback surface.", "No local result establishes useful online adaptation, contamination resistance, or recoverability.", ["arXiv:2407.04620, Abstract and Sections 1-3"]),
    mapping("ext_titans_2025", "Provides a neural long-term-memory and test-time memorization comparator.", "Mutable neural memory is not exact durable state; source results are not reproduced.", ["arXiv:2501.00663, Abstract and memory architecture sections"]),
    mapping("ext_kan_2024", "Defines KANs through learned univariate edge functions and supplies scientific/symbolic demonstrations.", "It does not establish a general replacement for MLPs, attention, or language-model backbones.", ["arXiv:2404.19756, Abstract and Sections 2-4"]),
    mapping("ext_kan_or_mlp_fairer_comparison_2024", "Supplies a critical matched-accounting objection for KAN-versus-MLP claims.", "One comparison does not settle every task or implementation; it sets a fairness requirement.", ["arXiv:2407.16674, Abstract and experimental setup"]),
    mapping("ext_neural_turing_machines_2014", "Provides a differentiable controller over external memory and algorithmic-task tests.", "Toy-distribution performance does not establish reliable exact memory or general computation.", ["arXiv:1410.5401, Abstract and Sections 1-3"]),
    mapping("ext_differentiable_neural_computer_2016", "Extends learned control over dynamic external memory and structured tasks.", "Source-reported tasks do not establish scalable, exact, or rollback-safe memory.", ["Nature 538, 471-476 (2016), Abstract and architecture description"]),
    mapping("ext_liquid_time_constant_networks_2021", "Provides a continuous-time recurrent comparator with input-dependent time constants.", "Reported time-series results do not establish broad cognitive or hardware superiority.", ["AAAI 2021 paper, Abstract and method sections"]),
    mapping("ext_dreamcoder_2020", "Provides library learning and reusable program abstraction as a comparator for verified compression and future-search reduction.", "DreamCoder's reported domains do not validate OneCell, the frozen-core ratchet, or local library growth.", ["arXiv:2006.08381, Abstract and Sections 1-3"]),
    mapping("ext_tiny_recursive_model_2025", "Provides the primary tiny weight-tied recursive reasoning candidate and its reported narrow puzzle results.", "The source does not establish general reasoning, language capability, deep effective recursion, or total-system simplicity.", ["arXiv:2510.04871, Abstract and architecture/evaluation sections"]),
    mapping("ext_trm_arc_agi_analysis_2025", "Provides a critical audit of TRM task-identity dependence, 1000-sample voting, and effective recursion depth.", "The technical note is not a local reproduction and does not by itself settle every TRM variant.", ["arXiv:2512.11847v2, Abstract and behavioral analysis"]),
    mapping("ext_tiny_autoregressive_recursive_models_2026", "Provides a compute-matched mechanism ablation that reports no reliable advantage from the full autoregressive TRM mechanism.", "Small character-level algorithmic tasks do not settle all recurrent architectures; the result sets a controlled-comparison requirement.", ["arXiv:2603.08082, Abstract and controlled experimental design"]),
    mapping("ext_unimatrix_2026", "Provides a current negative result for compressed recurrent associative recall and a positive source-reported contrast after adding sparse slots and pointer-level routing.", "One small-scale preprint does not establish universal memory limits or a locally reproduced architecture result.", ["arXiv:2604.25930, Abstract and associative-recall results"]),
    mapping("ext_memory_caching_2026", "Provides a growing-memory recurrent comparator that interpolates between fixed recurrent state and cached addressable state.", "The source reports that Transformers remain strongest on its in-context recall tasks; no local result or universal complexity conclusion follows.", ["arXiv:2602.24281, Abstract and memory-caching design"]),
]


NEW_CHAPTER = {
    "id": CHAPTER_ID,
    "title": "Replaceable Cognitive Substrates: Beyond Transformer Monoculture",
    "file": "chapters/replaceable-cognitive-substrates-beyond-transformer-monoculture.qmd",
    "status": "conceptual",
    "evidence_level": "argument",
    "claim_label": "Design rationale",
    "source_ids": [row["id"] for row in NEW_RECORDS] + EXISTING_SOURCE_IDS,
    "source_queue": {
        "primary": ["scf", "rmi", "benchmaxxing", "corben_chatgpt_kiss_irreducible_intelligence_2026", "corben_chatgpt_onecell_theseus_2026"],
        "supporting": [row["id"] for row in NEW_RECORDS if row["id"].startswith("ext_")] + ["ext_mamba_2023", "ext_retnet_2023", "ext_universal_transformer_2019", "ext_dynamic_compute_recurrent_transformers_2026", "ext_dreamcoder_2020"],
        "variants": [],
        "connector_or_recovery": [],
        "handoff_or_recovery_notes": ["Accepted after the 2026-07-15 distinct-interface review; the chapter owns the Cognitive Kernel ABI and architecture-RSI evidence program, while existing routing, readiness, rollback, recurrence, deliberation, and self-improvement chapters retain their established interfaces."],
    },
    "problem": "The stack can claim replaceability while silently baking Transformer token, state, memory, checkpoint, and serving assumptions into every surrounding layer, making architectural improvement expensive, unsafe, and self-ratifying.",
    "insufficient": "An architecture catalog, parameter-count comparison, asymptotic complexity claim, single benchmark, synthetic recall result, source-reported win, or tiny central model with hidden retrieval/search/tool burden does not establish a simpler, better, safer, or replaceable cognitive substrate.",
    "core_claim": "For an exact task family, consumer, modality, model and state version, memory contract, hardware/runtime, authority and rights envelope, resource budget, evaluator, fallback, rollback, and time horizon, learned cognition should be supplied through a typed Cognitive Kernel ABI whose implementations are admitted only by matched strong baselines, exact state and memory semantics, proposal-versus-effect separation, evaluator independence, complete lifecycle cost, failure and residual retention, checkpoint compatibility, and causal ablation.",
    "claim_source_mappings": SOURCE_MAPPINGS,
    "mechanism": [
        "Place initialize, propose, consume-receipt, checkpoint, restore, cost, capability, architecture identity, state schema, assistance disclosure, and non-claim operations behind a typed Cognitive Kernel ABI.",
        "Keep identity, authority, effects, receipts, provenance, program counters, values, and durable state exact while allowing prediction, relevance, uncertainty, and heuristic proposals to remain latent.",
        "Route reflex, reaction, deliberation, search, and specialist work above the ABI so a route can select one kernel, a composition, or a deterministic primitive without widening authority.",
        "Qualify kernels with equal-active-parameter and equal-total-lifecycle-cost tournaments, matched strong baselines, independent evaluators, adverse controls, rollback, reproduction, and transfer.",
        "Separate recurrent computation from addressable memory by preregistering recurrent-state size, sparse-slot capacity, cache growth, pointer fusion, exact-memory controls, storage, lookup, invalidation, migration, and deletion cost.",
        "For tiny-recursive candidates, preregister canonical single-pass, matched sampling/voting, blank/random/unseen identity, marginal utility by recursion step, learned stopping, and progressive mechanism ablations.",
        "Govern architectural RSI as candidate generation, training, shadowing, canarying, promotion, composition, narrowing, rollback, retirement, and descendant invalidation—not merely weight updates.",
        "Treat OneCell as one falsifiable compact recurrent candidate: shared transition weights, typed state lanes, exact external state, outer branch-preserving search, verified abstraction accumulation, and a frozen-core ratchet.",
    ],
    "interfaces": [
        "Routing Heads and Specialist Cores consumes qualified kernel capability cards and emits bounded route requests.",
        "Stable Capability Fields owns stable capability identity, qualification state, implementation versions, and lifecycle events.",
        "Capability Replacement and Rollback owns migration, effect-complete restore, descendant invalidation, and retirement transactions.",
        "Virtual Context Memory and memory chapters own exact source, custody, retrieval, and durable-memory contracts rather than delegating them to hidden activations.",
        "Governed Deliberation owns outer search, verifier use, budget allocation, stopping, fallback, and abstention above a kernel proposal interface.",
        "Recursive Self-Improvement Boundaries owns who may propose, evaluate, approve, promote, roll back, and retire architecture candidates.",
        "Integrated Reference Architecture must join one same-task substrate swap and one mixed-kernel trace through evidence, authority, cost, and recovery records.",
    ],
    "invariants": [
        "A kernel returns proposals and evidence handles; it cannot commit external effects or mint its own authority.",
        "Substrate replacement cannot widen authority, weaken protected predicates, erase residuals, or silently change the evaluation contract.",
        "Every routed result records kernel identity, version, state schema, checkpoint lineage, assistance, evaluator, costs, residuals, and fallback.",
        "Checkpoint migration either preserves every declared exact field under an independently checked adapter or rejects before effect.",
        "Mutable test-time state is versioned, attributable, revocable, inspectable at its declared boundary, and recoverable without treating model weights as the only state.",
        "Deterministic tools, retrieval, search, compilers, adapters, and verifiers are separately credited in quality and cost accounting.",
        "OneCell, KAN, Mamba, Transformer, or any later architecture remains a candidate until the exact qualification packet passes; no name receives architectural privilege.",
    ],
    "failure_modes": [
        "Transformer monoculture leaks token, KV-cache, positional, and checkpoint assumptions into supposedly neutral stack contracts.",
        "Architecture tourism lists fashionable models without connecting them to exact workloads, failure modes, interfaces, or falsifiers.",
        "Benchmark laundering promotes a source-reported or cherry-picked win without matched data, compute, parameters, wall time, hardware, assistance, or evaluator quality.",
        "Asymptotic laundering substitutes linear or subquadratic notation for end-to-end quality, kernel efficiency, memory traffic, training cost, and lifecycle burden.",
        "Tiny-core laundering hides intelligence and cost in a large adapter, retrieval corpus, deterministic tool, search budget, verifier, or hand-authored skill library.",
        "State amnesia checkpoints model weights but loses optimizer, scheduler, RNG, cache, online memory, adapter, backup, and descendant state.",
        "Latent-exact collapse asks a learned hidden state to preserve identity, authority, receipts, effects, or legal/governance obligations exactly.",
        "Self-ratifying architecture change lets a candidate design or select its own evaluator, training data, acceptance threshold, or promotion record.",
        "Router multiplication adds translation, calibration, maintenance, and correlated-failure burden that exceeds any substrate gain.",
        "Frozen-core theater claims cumulative intelligence when gains come from answer-bearing retrieval, benchmark-authored tools, contamination, or expanding outer compute.",
        "Memory relabeling calls compressed recurrent state an attention replacement without measuring exact recall, then adds growing caches or pointer slots without charging their addressable-memory burden.",
        "Recursion-depth laundering credits nominal recursive steps or a tiny parameter count when task identity, augmentation, sampling, voting, or the first few useful steps supply the result.",
    ],
    "minimal_implementation": "A finite Cognitive Kernel ABI transition model and independent Python consumer now exercise one nine-event mixed Transformer-to-selective-state-space-to-KAN-to-fallback trace, proposal/effect separation, exact checkpoint identity, non-increasing authority, revocation, migration compatibility, custody fields, two receipt-bound commits, fifteen rejected cases, and twelve rejecting event mutations. This is schema/transition evidence only: no real Transformer, Mamba, KAN, recurrent, graph, or program-synthesis kernel runs behind the ABI. The first empirical minimum still requires three genuinely different kernels, matched Transformer and simple baselines, equal-active-parameter and equal-total-cost views, natural tasks, state migration and restore over real full-state checkpoints, and independently observed effects; until then the core claim remains argument.",
    "beyond_state_of_art": "A mature result would compare strong Transformer, recurrent/state-space, long-convolution or test-time-state, tiny-recursive, and exact-search/controller lanes on natural, algorithmic, long-context, continual, multimodal, control, and exact-execution workloads under the same governed ABI. It would separate recurrent compute from fixed, cached, sparse-slot, pointer-routed, exact, and attention memory; freeze task identity, sampling, voting, stopping, and useful-recursion-depth controls; report accepted usefulness, unsafe release, abstention, calibration, extrapolation, latency, memory, energy where measurable, training, search, verification, repair, routing, migration, maintenance, governance, fallback, and failure cost; use independent evaluators and hidden controls; reproduce and transfer results; and causally test whether route diversity, verified abstraction, or frozen-core accumulation reduces future search without hiding external intelligence. No current repository result meets that bar.",
    "codex_tests": [
        {"name": "Cognitive Kernel ABI conformance and malicious-kernel rejection", "purpose": "Check typed proposals, receipt consumption, exact state identity, authority ceilings, checkpoint/restore, cost disclosure, fallback, and rejected forgery or omitted-state controls.", "status": "implemented bounded synthetic ABI under P2; empirical kernel conformance remains planned under P5", "implementation_status": "implemented", "result_status": "passes 16-case independent trace checker with 12 rejecting mutations; no real kernel or benchmark"},
        {"name": "Matched heterogeneous-kernel tournament", "purpose": "Compare at least three genuinely different kernels under equal-active-parameter and equal-total-lifecycle-cost views; separate recurrent compute from addressable memory; and apply identity, sampling, voting, stopping, and recursion-step controls on preregistered workloads and strong baselines.", "status": "planned under P5", "implementation_status": "planned", "result_status": "not run"},
        {"name": "Frozen-core verified-abstraction ratchet", "purpose": "Test whether held-out future search cost falls while central parameters remain fixed, without answer-bearing retrieval, hidden assistance, or growing unreported compute.", "status": "planned under P5", "implementation_status": "planned", "result_status": "not run"},
        {"name": "Governed architectural-RSI lifecycle", "purpose": "Exercise candidate generation, independent evaluation, shadow, canary, promotion denial, rollback, retirement, and descendant invalidation without self-approval.", "status": "planned under P5", "implementation_status": "planned", "result_status": "not run"},
    ],
    "lean_module": "AsiStackProofs.ReplaceableCognitiveSubstrates",
    "proof_targets": [
        {
            "tag": "lean:cognitive_kernel.abi_trace_invariants",
            "module": "AsiStackProofs.ReplaceableCognitiveSubstrates",
            "target": "A finite Cognitive Kernel ABI trace keeps proposals separate from effects, preserves non-increasing authority and declared exact checkpoint state, rejects revoked kernels and incompatible migrations, and preserves fallback, evaluator, assistance, cost, evidence, and residual ownership across mixed-kernel routes.",
            "status": "implemented"
        }
    ],
    "draft_maturity": "v0.2 manuscript draft",
    "open_evidence_gaps": [
        "No real-model ABI implementation; the current common ABI and independent checker cover finite synthetic transition records only.",
        "No matched architecture tournament, natural workload, reproduction, transfer, or hardware-aware cost packet.",
        "The finite model proves and checks proposal/effect separation, authority and checkpoint preservation, revocation, fallback, and mixed-family lineage only inside its declared transition schema; no real checkpoint translation, effect service, or deployed enforcement exists.",
        "No OneCell implementation, frozen-core ratchet, verified abstraction learner, or hidden-complexity ablation.",
        "No governed architecture candidate has passed shadow, canary, rollback, retirement, or descendant-invalidation tests.",
    ],
}


def main() -> None:
    inventory = json.loads(INVENTORY.read_text(encoding="utf-8"))
    by_id = {row["id"]: row for row in inventory}
    new_ids = {row["id"] for row in NEW_RECORDS}
    for row in NEW_RECORDS:
        by_id[row["id"]] = row
    for source_id in EXISTING_SOURCE_IDS:
        record = by_id[source_id]
        targets = record.setdefault("chapter_targets", [])
        if CHAPTER_ID not in targets:
            targets.append(CHAPTER_ID)
    old_order = [row["id"] for row in inventory if row["id"] not in new_ids]
    inventory = [by_id[source_id] for source_id in old_order] + NEW_RECORDS

    structure = json.loads(STRUCTURE.read_text(encoding="utf-8"))
    part = next(row for row in structure["parts"] if row["id"] == "routing-compression-representation-substrates")
    chapters = [row for row in part["chapters"] if row["id"] != CHAPTER_ID]
    routing_index = next(index for index, row in enumerate(chapters) if row["id"] == "routing-heads-and-specialist-cores")
    chapters.insert(routing_index + 1, NEW_CHAPTER)
    part["chapters"] = chapters

    INVENTORY.write_text(json.dumps(inventory, indent=2) + "\n", encoding="utf-8")
    STRUCTURE.write_text(json.dumps(structure, indent=2) + "\n", encoding="utf-8")
    print(f"Integrated {CHAPTER_ID}: {len(inventory)} sources, {sum(len(p['chapters']) for p in structure['parts'])} chapters.")


if __name__ == "__main__":
    main()
