#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];STRUCTURE=ROOT/'book_structure.json';TRIAGE=ROOT/'proofs/proof_triage.json';REVIEWS=ROOT/'proofs/proof_rationalization_reviews.json'
CHAPTER='recursive-self-improvement-boundaries';MODULE='AsiStackProofs.SelfImprovementRefinement'
TARGETS={
'lean:self_improvement.boundary.operational_invariant':'A complete finite self-improvement governance trace preserves exact protected-partition and non-widening-authority records through bounded replacement handoff, returned outcome reconciliation, and successor-version readmission without support or external-effect authority.',
'lean:self_improvement.boundary.failure_blocks_promotion':'Protected-invariant weakening, authority widening, self-ratified objectives, missing independent evaluation or monitoring, stale gates, missing rollback or residual custody, and support or release laundering block the reachable lifecycle.',
'lean:self_improvement.boundary.transition_route_envelope':'A versioned eight-stage self-improvement proposal-to-outcome lifecycle reaches all 118 finite routes, binds exact identity and full-state custody, and requires material-change invalidation before version-2 readmission.'}
REFS={'countermodel_refs':['lean/AsiStackProofs/SelfImprovementRefinement.lean#self_improvement_refinement_routes'],'mutation_refs':['scripts/validate_self_improvement_refinement.py#mutations'],'consumer_refs':['docs:self_improvement_refinement','evidence_quality:model_adequacy_dossiers/self-improvement-refinement.md'],'runtime_consumer_refs':['scripts/validate_self_improvement_refinement.py','schemas/self_improvement_refinement.schema.json','experiments/self_improvement_refinement/results/2026-07-16-local.json'],'replacement_refs':['proof-model:self-improvement-refinement.v1','lean/AsiStackProofs/SelfImprovementRefinement.lean']}
def attach(row):
 for k,v in REFS.items():row[k]=list(dict.fromkeys([*row.get(k,[]),*v]))
def main():
 s=json.loads(STRUCTURE.read_text());c=next(c for p in s['parts'] for c in p['chapters'] if c['id']==CHAPTER)
 for t in c['proof_targets']:
  if t['tag'] in TARGETS:t['module']=MODULE;t['target']=TARGETS[t['tag']]
 c['lean_module']='AsiStackProofs.SafetyCriticalLifecycle; AsiStackProofs.SelfImprovement; AsiStackProofs.SelfImprovementRefinement'
 c['minimal_implementation']='The exact current minimum preserves the 3-valid/10-invalid self-improvement fixture, 4-valid/5-invalid readiness fixture, 5-valid/9-invalid replacement fixture, two-transaction/three-control replacement trace, eight-trace/six-control intent bridge, three-seed/twelve-arm fixed update result, Open-Ended Improvement governor handoff, 22 legacy SelfImprovement declarations, and shared safety lifecycle inside an eight-stage, 118-route proposal-to-outcome lifecycle with 129/129 rejecting mutations, one bounded replacement handoff, one returned outcome reconciliation, and one protocol-version-2 readmission witness. The update result retains four no-change dispositions and three exact local rollbacks; the Open-Ended challenger retains zero threshold passes; support/effect remain none. No adaptive proposal generation, live self-modification, natural useful improvement, evaluator or monitor competence, live authority enforcement, production replacement, semantic recovery, effect-complete rollback, transfer, chapter-core transition, or SOTA result exists.'
 c['open_evidence_gaps']=['No preregistered natural candidate-authored change has compared no-update, cheaper intervention, human-authored, CI/CD, archive-search, and strongest source-system baselines under matched task, model, tool, data, compute, latency, verification, and human budgets.','No separately operated evaluator, monitor, approval service, capability-field governor, replacement runner, or compensation process has exercised a live proposal through effect-bearing canary, observed outcome, rollback or commit, descendant invalidation, and terminal reconciliation.','The eight-stage lifecycle, 118-route consumer, and 129 rejecting mutations establish only finite authored governance custody; objective legitimacy, rights premises, state completeness, evaluator and monitor records, effects, rollback, restoration, remediation, compensation, and invalidations remain trusted inputs.','No independent implementation or transfer site has reproduced the lifecycle or established useful improvement, evaluator independence, deception detection, semantic recovery, effect-complete rollback, recursive composition safety, or a joint usefulness/safety/cost/rights frontier.']
 c['codex_tests']=[x for x in c['codex_tests'] if not(isinstance(x,dict) and x.get('name')=='Recursive self-improvement proposal-to-outcome lifecycle refinement')]
 c['codex_tests'].append({'name':'Recursive self-improvement proposal-to-outcome lifecycle refinement','implementation_status':'implemented','result_status':'passes seven inherited suites, eight reachable stages, all 118 routes, and 129/129 rejecting mutations; one bounded replacement handoff consumes one outcome reconciliation and returns only through version-2 readmission; support/effect none; no useful-improvement, evaluator/monitor-competence, live replacement, safety, release, transfer, or support claim'})
 STRUCTURE.write_text(json.dumps(s,indent=2)+'\n')
 t=json.loads(TRIAGE.read_text())
 for row in t['records']:
  if row['tag'] in TARGETS:row['module']=MODULE;row['formal_target']=TARGETS[row['tag']];row['rationale']='Reachable proposal-to-outcome lifecycle with prospective scope, exact proposal and full-state custody, independent evaluation/monitor records, bounded replacement handoff, outcome reconciliation, successor-version readmission, 118 routes, 129 rejecting mutations, and no support/effect authority.'
 TRIAGE.write_text(json.dumps(t,indent=2)+'\n')
 r=json.loads(REVIEWS.read_text())
 for target in TARGETS:
  row=r['target_reviews'][target];attach(row);row['semantic_role']='Reachable scope-to-proposal-to-implementation-to-state-to-evaluation-to-adjudication-to-replacement-outcome lifecycle with exact identity, authority, full-state, rollback, descendant, residual, and successor-version boundaries.';row['assumptions']=['All self-model, objective, rights, partition, proposal, implementation, full-state, evaluator, monitor, baseline, outcome, effect, rollback, restoration, remediation, compensation, approval, evidence-transition, invalidation, and ownership records are trusted inside the finite authored model.'];row['excluded_effects']=['Objective legitimacy, evaluator or monitor competence and independence, useful improvement, deception detection, live authority enforcement, production replacement, semantic recovery, effect-complete rollback, compensation efficacy, recursive composition, safety, readiness, release, deployment, reproduction, transfer, SOTA, AGI, ASI, and chapter-core support are excluded.'];row['review_rationale']='Join three disconnected targets and seven bounded evidence suites into a reachable versioned proposal-to-outcome lifecycle, independent replay, 118 routes, and 129 rejecting mutations.'
 for k,row in r['theorem_reviews'].items():
  if k.startswith('lean/AsiStackProofs/SelfImprovement.lean::'):attach(row)
 REVIEWS.write_text(json.dumps(r,indent=2)+'\n');print('Integrated Recursive Self-Improvement refinement across 3 targets and 22 frozen declarations.')
if __name__=='__main__':main()
