#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];S=ROOT/'book_structure.json';T=ROOT/'proofs/proof_triage.json';R=ROOT/'proofs/proof_rationalization_reviews.json';MODULE='AsiStackProofs.HiveLifecycleRefinement'
TARGETS={'lean:personal_hives.scheduling.operational_invariant':'A reachable Hive lifecycle preserves exact job, principal, contract, registry, candidate-set, selected-node, policy, authority, lease, evaluator, consumer, and residual custody from policy binding through acknowledged closure while separating dispatch, useful-outcome, recovery, support, and external-effect accounting.','lean:personal_hives.policy_first.failure_blocks_promotion':'Incomplete identity, data, tool, approval, registry, candidate-denominator, least-authority, locality, budget, energy, or dropout policy blocks selection before optimization.','lean:personal_hives.approval_gate.failure_blocks_promotion':'A high-risk Hive job cannot execute without a bound approval receipt tied to the exact job and lease.','lean:personal_hives.federation_lease.operational_invariant':'External Hive access cannot receive a lease without federation, sandbox, scope, evidence-obligation, expiration, and revocation custody bound to the selected node.','lean:personal_hives.work_admission.lifecycle_route':'The independent consumer preserves all forty-seven policy, selection, lease, partition, execution, reconciliation, recovery, revocation, and closure outcomes.','lean:personal_hives.partitioned_authority.fixture_bridge':'Partitioned stale authority quarantines before mutation only with denial and no-mutation evidence; otherwise the lifecycle requests evidence and never infers deployed partition tolerance or support.'}
PREFIX='lean/AsiStackProofs/PersonalComputeHives.lean::';RETIRED={PREFIX+n for n in ['admitted_hive_job_has_identity_data_tool_federation_and_approval_checks','faster_forbidden_node_cannot_be_selected','high_risk_hive_job_without_bound_approval_cannot_execute','external_hive_access_requires_lease_scope_sandbox_evidence_expiration_and_revocation','partitioned_authority_fixture_bridge']}
REFS={'countermodel_refs':['lean/AsiStackProofs/HiveLifecycleRefinement.lean#countermodels'],'mutation_refs':['scripts/validate_hive_lifecycle_refinement.py#mutations'],'consumer_refs':['docs:hive_lifecycle_refinement','evidence_quality:model_adequacy_dossiers/hive-lifecycle-refinement.md'],'runtime_consumer_refs':['scripts/validate_hive_lifecycle_refinement.py','schemas/hive_lifecycle_refinement.schema.json','experiments/hive_lifecycle_refinement/results/2026-07-15-local.json','scripts/validate_hive_admission.py','scripts/validate_partitioned_authority_fixture.py'],'replacement_refs':['proof-model:hive-lifecycle-refinement.v1','lean/AsiStackProofs/HiveLifecycleRefinement.lean']}
def attach(x):
 for k,v in REFS.items():x[k]=list(dict.fromkeys([*x.get(k,[]),*v]))
def main():
 s=json.loads(S.read_text());c=next(c for p in s['parts'] for c in p['chapters'] if c['id']=='personal-compute-hives-and-federated-edge-intelligence')
 for x in c['proof_targets']:
  if x['tag'] in TARGETS:x['module']=MODULE;x['target']=TARGETS[x['tag']]
 c['lean_module']='AsiStackProofs.PersonalComputeHives; AsiStackProofs.HiveLifecycleRefinement';c['codex_tests']=[x for x in c['codex_tests'] if not(isinstance(x,dict)and x.get('name')=='Hive policy-to-closure lifecycle refinement')];c['codex_tests'].append({'name':'Hive policy-to-closure lifecycle refinement','implementation_status':'implemented','result_status':'passes two exact suites, 47 routes, seven reachable stages, and 53/53 rejecting mutations; dispatch, useful-outcome, recovery, support, and effects stay separate; no deployed scheduler/federation, partition tolerance, availability, security, privacy, energy, dropout-recovery, useful-work, transfer, or support claim'});S.write_text(json.dumps(s,indent=2)+'\n')
 t=json.loads(T.read_text())
 for x in t['records']:
  if x['tag'] in TARGETS:x['module']=MODULE;x['formal_target']=TARGETS[x['tag']];x['rationale']='Reachable seven-stage Hive lifecycle with exact custody, two bounded suites, 47 routes, 53 rejecting mutations, and no support/effect authority.'
 T.write_text(json.dumps(t,indent=2)+'\n');r=json.loads(R.read_text())
 for target in TARGETS:
  x=r['target_reviews'][target];attach(x);x['semantic_role']='Reachable policy, selection, lease, partition-aware execution, reconciliation, recovery, revocation, and closure lifecycle.';x['assumptions']=['All identity, policy, authority, lease, partition, receipt, outcome, recovery, revocation, and acknowledgment fields are trusted inside the finite authored model.'];x['excluded_effects']=['Attestation, policy correctness, distributed execution, sandbox enforcement, partition tolerance, availability, privacy, security, energy, recovery efficacy, useful work, transfer, SOTA, and support are excluded.'];x['review_rationale']='Replace policy projections and authored fixture summary with a reachable Hive lifecycle, two exact suites, forty-seven routes, and 53 rejecting mutations.'
 ids=[k for k in r['theorem_reviews'] if k.startswith(PREFIX)]
 for k in ids:attach(r['theorem_reviews'][k])
 for k in RETIRED:x=r['theorem_reviews'][k];x['review_state']='terminally_dispositioned';x['disposition']='replace_with_stronger_model';x['review_rationale']='Frozen lineage retained; declaration physically retired because it projected an assumed policy or normalized an authored fixture summary now subsumed by the reachable refinement.'
 R.write_text(json.dumps(r,indent=2)+'\n');print(f'Integrated Hive refinement across 6 targets and {len(ids)} frozen declarations; 5 retired.')
if __name__=='__main__':main()
