#!/usr/bin/env python3
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PATH=ROOT/"validation/registry.json";SCRIPT="validate_artifact_compression_refinement.py"
ARTIFACTS=["scripts/validate_artifact_compression_refinement.py","schemas/artifact_compression_refinement.schema.json","experiments/artifact_compression_refinement/results/2026-07-15-local.json","docs/artifact_compression_refinement.md","evidence_quality/model_adequacy_dossiers/artifact-compression-refinement.md","lean/AsiStackProofs/ArtifactCompressionRefinement.lean","scripts/validate_rankfold_public_safe_probe.py","scripts/validate_rankfold_artifact_import.py","tests/fixtures/protocol_records/compressed_artifact_record.valid.json"]
r=json.loads(PATH.read_text());r["units"]=[u for u in r["units"] if u.get("script")!=SCRIPT];order=len(r["units"])+1
r["units"].append({"id":f"{SCRIPT}:{order}","order":order,"script":SCRIPT,"args":[],"execution_tier":"deep","validation_class":"proof_or_evidence_gate","input_contract":"Reachable artifact-compression lifecycle, exact fixture, RAW0 replay, NEURAL0 import, no-change decisions, independent route consumer, schema, receipt, and adequacy dossier.","input_artifacts":ARTIFACTS,"output_contract":"Reject identity, source-custody, decoder, reconstruction, probe, fallback, utility, rights, cost, outcome, closure, support, and effect failures.","output_assertions":["eight reachable stages","53 routes","44 rejected non-accepting mutations","five SHA-256-bound source artifacts","support and external effect none"],"claim_scope":"One finite authored artifact-to-consumption policy and exact bounded fixture/replay/import identities.","negative_controls":"validator_owned_artifact_compression_route_mutations","negative_control_cases":["identity, policy, decoder, evidence, event, or authority substitution","missing source, manifest, reconstruction, probe, fallback, cost, outcome, or closure","raw-ratio, support, or effect laundering"],"prohibited_inference":"No codec correctness, NeuralFold reproduction, useful compression, semantic preservation, downstream utility, deployed fallback, safety, transfer, SOTA, AGI, ASI, or support.","contract_precision":"inherited","semantic_review_state":"checked_artifact_to_consumption_lifecycle_not_codec_utility_or_support_authority"})
req=list(r["required_artifacts"])
for a in ARTIFACTS:
 if a not in req:req.append(a)
r["required_artifacts"]=req;r["summary"]={"required_artifact_count":len(req),"unit_count":len(r["units"])};PATH.write_text(json.dumps(r,indent=2)+"\n");print(f"Registered {SCRIPT}: {len(r['units'])} units, {len(req)} artifacts.")
