#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; REGISTRY=ROOT/"validation/registry.json"; SCRIPT="validate_context_certificate_refinement.py"
ARTIFACTS=["scripts/validate_context_certificate_refinement.py","schemas/context_certificate_refinement.schema.json","experiments/context_certificate_refinement/results/2026-07-15-local.json","docs/context_certificate_refinement.md","evidence_quality/model_adequacy_dossiers/context-certificate-refinement.md","lean/AsiStackProofs/ContextCertificateRefinement.lean","schemas/semantic_page_certificate.schema.json","tests/fixtures/protocol_records/semantic_page_certificate.valid.json","scripts/validate_context_admission_adequacy.py","experiments/context_admission_adequacy/fixtures"]
def main()->None:
    value=json.loads(REGISTRY.read_text()); value["units"]=[u for u in value["units"] if u.get("script")!=SCRIPT]; order=len(value["units"])+1
    value["units"].append({"id":f"validate_context_certificate_refinement:{order}","order":order,"script":SCRIPT,"args":[],"execution_tier":"deep","validation_class":"proof_or_evidence_gate","input_contract":"Reachable Lean certificate model, public certificate schema and canonical fixture, complete eight-scenario/twelve-certificate inventory, admission harness, independent consumer, result schema, receipt, and adequacy dossier.","input_artifacts":ARTIFACTS,"output_contract":"Reject provenance or contract substitution, authority widening, stale epochs, missing declarations or receipts, deletion gaps, unpermitted use, taint, revocation, support laundering, fixture drift, and support promotion.","output_assertions":["twelve schema-valid certificate projections remain distinct from eight whole-scenario judgments","three valid and five invalid admission fixtures","five reachable events","sixty-four rejected mutations","no support-state effect"],"claim_scope":"One finite single-source/single-use sequential certificate lifecycle, one canonical fixture, and twelve certificate records across eight hand-authored scenarios only.","negative_controls":"validator_owned_model_source_and_fixture_mutations","negative_control_cases":["source or contract substitution","authority escalation","stale epoch or missing receipt","deletion closure gap","unpermitted use or support laundering","taint or revocation"],"prohibited_inference":"Does not establish source/payload truth, transformation or omission fidelity, verifier independence, deployed enforcement, concurrent revocation, deletion propagation, natural-workload usefulness, reproduction, transfer, safety, SOTA, AGI, ASI, or chapter-core support.","contract_precision":"inherited","semantic_review_state":"checked_structured_context_certificate_refinement_not_content_truth_external_or_deployed"})
    required=list(value["required_artifacts"])
    for a in ARTIFACTS:
        if a not in required: required.append(a)
    value["required_artifacts"]=required; value["summary"]={"required_artifact_count":len(required),"unit_count":len(value["units"])}; REGISTRY.write_text(json.dumps(value,indent=2)+"\n"); print(f"Registered {SCRIPT}: {len(value['units'])} units, {len(required)} artifacts.")
if __name__=="__main__": main()
