#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REGISTRY=ROOT/'validation/registry.json';SCRIPT='validate_self_improvement_refinement.py'
ARTIFACTS=['scripts/validate_self_improvement_refinement.py','schemas/self_improvement_refinement.schema.json','experiments/self_improvement_refinement/results/2026-07-16-local.json','docs/self_improvement_refinement.md','evidence_quality/model_adequacy_dossiers/self-improvement-refinement.md','lean/AsiStackProofs/SelfImprovementRefinement.lean','lean/AsiStackProofs/SelfImprovement.lean','scripts/validate_self_improvement_boundaries.py','scripts/validate_readiness_residual_gates.py','scripts/validate_capability_replacement.py','scripts/validate_capability_replacement_trace_probe.py','scripts/validate_intent_governed_replacement_bridge.py','scripts/validate_post_v2_update_causality.py','scripts/validate_open_ended_improvement_refinement.py']
def main():
 v=json.loads(REGISTRY.read_text());v['units']=[u for u in v['units'] if u.get('script')!=SCRIPT];order=len(v['units'])+1
 v['units'].append({'id':f'{SCRIPT}:{order}','order':order,'script':SCRIPT,'args':[],'execution_tier':'deep','validation_class':'proof_or_evidence_gate','input_contract':'Reachable Lean self-improvement proposal-to-outcome lifecycle, seven exact inherited suites, independent consumer, result schema, receipt, and model-adequacy dossier.','input_artifacts':ARTIFACTS,'output_contract':'Reject identity substitution, incomplete scope/proposal/implementation/full-state/evaluation/adjudication/outcome/readmission records, protected weakening, authority widening, stale gates, replay, support assignment, and external-effect requests.','output_assertions':['seven exact inherited suites','eight reachable stages and 118 routes','129 rejected mutations','one bounded replacement handoff, one returned outcome reconciliation, and successor-version readmission','no support-state or external-effect authority'],'claim_scope':'One finite authored self-improvement governance lifecycle over synthetic records and fixed local results only.','negative_controls':'validator_owned_identity_scope_proposal_state_evaluation_outcome_readmission_mutations','negative_control_cases':['transition, self-model, consumer, partition, authority, objective, proposal, implementation, evaluator, monitor, baseline, inventory, replacement, residual, policy, stop, or version substitution','missing scope, proposal, boundary, full-state, evaluation, approval, rollback, outcome, compensation, invalidation, or readmission record','self-ratified objective, protected weakening, authority widening, candidate promotion, support promotion, or release authority laundering','wrong stage, replay, support assignment, or external-effect request'],'prohibited_inference':'Does not establish objective legitimacy, evaluator or monitor competence, useful improvement, live authority enforcement, production replacement, semantic recovery, effect-complete rollback, compensation efficacy, recursive safety, readiness, release, deployment, reproduction, transfer, SOTA, AGI, ASI, or chapter-core support.','contract_precision':'inherited','semantic_review_state':'checked_structured_self_improvement_governance_lifecycle_not_useful_safe_deployed_or_support_authority'})
 req=list(v['required_artifacts'])
 for a in ARTIFACTS:
  if a not in req:req.append(a)
 v['required_artifacts']=req;v['summary']={'required_artifact_count':len(req),'unit_count':len(v['units'])};REGISTRY.write_text(json.dumps(v,indent=2)+'\n');print(f'Registered {SCRIPT}: {len(v["units"])} units, {len(req)} artifacts.')
if __name__=='__main__':main()
