#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REGISTRY=ROOT/'validation/registry.json';SCRIPT='validate_capability_threshold_refinement.py'
ARTIFACTS=['scripts/validate_capability_threshold_refinement.py','schemas/capability_threshold_refinement.schema.json','experiments/capability_threshold_refinement/results/2026-07-15-local.json','docs/capability_threshold_refinement.md','evidence_quality/model_adequacy_dossiers/capability-threshold-refinement.md','lean/AsiStackProofs/CapabilityThresholdRefinement.lean','scripts/validate_capability_threshold_commitment.py','experiments/capability_threshold_commitment/fixtures/cases.json','experiments/capability_threshold_commitment/results/2026-07-13-local.json']
def main():
 v=json.loads(REGISTRY.read_text());v['units']=[u for u in v['units'] if u.get('script')!=SCRIPT];order=len(v['units'])+1
 v['units'].append({'id':f'{SCRIPT}:{order}','order':order,'script':SCRIPT,'args':[],'execution_tier':'deep','validation_class':'proof_or_evidence_gate','input_contract':'Reachable Lean threshold lifecycle, exact inherited eight-case suite, independent consumer, result schema, receipt, and model-adequacy dossier.','input_artifacts':ARTIFACTS,'output_contract':'Reject identity substitution, incomplete scope/assessment/adjudication/control/exception/readiness/reassessment custody, replay, authority laundering, and support/effect leakage.','output_assertions':['eight exact inherited cases','forty-three routes and six reachable stages','forty-eight rejected mutations','readiness handoff followed by successor-version reassessment','no support-state or external-effect authority'],'claim_scope':'One finite authored capability-threshold record lifecycle plus the existing eight-case fixture only.','negative_controls':'validator_owned_identity_assessment_safeguard_exception_reassessment_authority_mutations','negative_control_cases':['capability, system, policy, release path, envelope, threshold, baseline, evaluator, safeguard, authority, residual, or version substitution','missing assessment, uncertainty, adjudication, safeguard, bypass, rollback, monitoring, exception, residual, authority, or release-path record','incomplete invalidation, ordinary-route blocking, or successor version','wrong stage, replay, support assignment, or external-effect request'],'prohibited_inference':'Does not establish capability, threshold validity or crossing, evaluator independence, safeguard efficacy, exception validity, readiness, safety, release authority, deployed invalidation, transfer, AGI, ASI, or chapter-core support.','contract_precision':'inherited','semantic_review_state':'checked_structured_repeated_threshold_lifecycle_not_measurement_deployed_or_support_authority'})
 req=list(v['required_artifacts'])
 for a in ARTIFACTS:
  if a not in req:req.append(a)
 v['required_artifacts']=req;v['summary']={'required_artifact_count':len(req),'unit_count':len(v['units'])};REGISTRY.write_text(json.dumps(v,indent=2)+'\n');print(f'Registered {SCRIPT}: {len(v["units"])} units, {len(req)} artifacts.')
if __name__=='__main__':main()
