#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; REGISTRY=ROOT/'validation/registry.json'; SCRIPT='validate_procedural_memory_refinement.py'
ARTIFACTS=['scripts/validate_procedural_memory_refinement.py','schemas/procedural_memory_refinement.schema.json','experiments/procedural_memory_refinement/results/2026-07-15-local.json','docs/procedural_memory_refinement.md','evidence_quality/model_adequacy_dossiers/procedural-memory-refinement.md','lean/AsiStackProofs/ProceduralMemoryRefinement.lean','scripts/validate_procedural_memory_loop.py','experiments/procedural_memory_loop/fixtures','scripts/validate_procedural_trace_promotion.py','experiments/procedural_trace_promotion/fixtures']
def main():
 v=json.loads(REGISTRY.read_text()); v['units']=[u for u in v['units'] if u.get('script')!=SCRIPT]; order=len(v['units'])+1
 v['units'].append({'id':f'{SCRIPT}:{order}','order':order,'script':SCRIPT,'args':[],'execution_tier':'deep','validation_class':'proof_or_evidence_gate','input_contract':'Reachable Lean procedure promotion/retirement lifecycle, two exact bounded suites, independent consumer, result schema, receipt, and model-adequacy dossier.','input_artifacts':ARTIFACTS,'output_contract':'Reject identity/lineage substitution, replay, authority leakage, incomplete trace and negative-example custody, abstraction gaps, failed verification/regression, missing qualification/rollback/monitoring/residual/retirement custody.','output_assertions':['two exact bounded suites','thirty-two routes and seven reachable stages','thirty-three rejected lifecycle mutations','one qualified route and receipt-bound retirement','no support-state or external-effect authority'],'claim_scope':'One finite authored procedure lifecycle plus two existing bounded fixture suites only.','negative_controls':'validator_owned_identity_lineage_lifecycle_authority_mutations','negative_control_cases':['procedure, source, trace, abstraction, regression, SCF, policy, consumer, or event substitution','missing negative examples or source/effect receipts','missing abstraction, verification, benchmark, SCF, rollback, monitoring, residual, acknowledgment, or retirement custody','support assignment or external-effect authority leak'],'prohibited_inference':'Does not establish natural trace mining, semantic abstraction, generated-tool correctness, verifier/regression quality, rollback effectiveness, deployed routing, monitoring, retirement, usefulness, causality, safety, reproduction, transfer, SOTA, AGI, ASI, or chapter-core support.','contract_precision':'inherited','semantic_review_state':'checked_structured_procedure_promotion_retirement_lifecycle_not_natural_deployed_or_support_authority'})
 req=list(v['required_artifacts'])
 for a in ARTIFACTS:
  if a not in req: req.append(a)
 v['required_artifacts']=req; v['summary']={'required_artifact_count':len(req),'unit_count':len(v['units'])}; REGISTRY.write_text(json.dumps(v,indent=2)+'\n'); print(f'Registered {SCRIPT}: {len(v["units"])} units, {len(req)} artifacts.')
if __name__=='__main__': main()
