#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REGISTRY=ROOT/"validation/registry.json";SCRIPT="validate_context_transaction_refinement.py"
ARTIFACTS=["scripts/validate_context_transaction_refinement.py","schemas/context_transaction_refinement.schema.json","experiments/context_transaction_refinement/results/2026-07-15-local.json","docs/context_transaction_refinement.md","evidence_quality/model_adequacy_dossiers/context-transaction-refinement.md","lean/AsiStackProofs/ContextTransactionRefinement.lean","scripts/validate_context_transaction_memory_store.py","experiments/context_transaction_memory_store/fixtures","scripts/validate_context_transaction_sequence_bridge.py","experiments/context_transaction_sequence_bridge/fixtures","schemas/context_transaction_record.schema.json"]
def main():
 v=json.loads(REGISTRY.read_text());v["units"]=[u for u in v["units"] if u.get("script")!=SCRIPT];order=len(v["units"])+1
 v["units"].append({"id":f"validate_context_transaction_refinement:{order}","order":order,"script":SCRIPT,"args":[],"execution_tier":"deep","validation_class":"proof_or_evidence_gate","input_contract":"Reachable Lean transaction model, exact 3/6 store and 2/4 sequence inventories and validators, transaction schema, independent consumer, result schema, receipt, and adequacy dossier.","input_artifacts":ARTIFACTS,"output_contract":"Reject snapshot, branch, mount, cell, version, visibility, receipt, taint, declassification, deletion, materialization, support, ordering, inventory, and support-state faults.","output_assertions":["three valid and six invalid store fixtures","two valid and four invalid sequence fixtures","six reachable events","seventy-eight rejected mutations","no support-state effect"],"claim_scope":"One finite single-cell sequential transaction model and fifteen hand-authored fixtures only.","negative_controls":"validator_owned_model_source_and_fixture_mutations","negative_control_cases":["missing or stale snapshot","branch or mount substitution","commit or read version fault","taint or declassification laundering","open deletion","support promotion without transition"],"prohibited_inference":"Does not establish serializability, linearizability, distributed isolation, crash recovery, replay determinism, deployed storage, erasure, side-channel safety, natural-workload usefulness, reproduction, transfer, safety, SOTA, AGI, ASI, or chapter-core support.","contract_precision":"inherited","semantic_review_state":"checked_structured_context_transaction_refinement_not_concurrent_distributed_or_deployed"})
 req=list(v["required_artifacts"])
 for a in ARTIFACTS:
  if a not in req:req.append(a)
 v["required_artifacts"]=req;v["summary"]={"required_artifact_count":len(req),"unit_count":len(v["units"])};REGISTRY.write_text(json.dumps(v,indent=2)+"\n");print(f"Registered {SCRIPT}: {len(v['units'])} units, {len(req)} artifacts.")
if __name__=="__main__":main()
