#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REGISTRY=ROOT/'validation/registry.json';SCRIPT='validate_open_ended_improvement_refinement.py'
ARTIFACTS=['scripts/validate_open_ended_improvement_refinement.py','schemas/open_ended_improvement_refinement.schema.json','experiments/open_ended_improvement_refinement/results/2026-07-16-local.json','docs/open_ended_improvement_refinement.md','evidence_quality/model_adequacy_dossiers/open-ended-improvement-refinement.md','lean/AsiStackProofs/OpenEndedImprovementRefinement.lean','lean/AsiStackProofs/OpenEndedImprovement.lean','scripts/validate_open_ended_improvement_campaign.py','experiments/open_ended_improvement_campaign/results/2026-07-13-local.json','scripts/validate_post_v2_update_causality.py','experiments/post_v2_update_causality/results/2026-07-10-local.json','scripts/validate_post_v2_1_outcomes.py','experiments/post_v2_1_evidence_program/results/2026-07-11-post-v2-1-outcomes.json']
def main():
 v=json.loads(REGISTRY.read_text());v['units']=[u for u in v['units'] if u.get('script')!=SCRIPT];order=len(v['units'])+1
 v['units'].append({'id':f'{SCRIPT}:{order}','order':order,'script':SCRIPT,'args':[],'execution_tier':'deep','validation_class':'proof_or_evidence_gate','input_contract':'Reachable Lean campaign-to-governor lifecycle, exact inherited admission and two stopped campaign suites, independent consumer, result schema, receipt, and model-adequacy dossier.','input_artifacts':ARTIFACTS,'output_contract':'Reject identity substitution, incomplete scope/generation/archive/evaluation/adjudication/handoff/readmission records, denominator or budget reset, score/admission and candidate/authority laundering, replay, support assignment, and external-effect requests.','output_assertions':['three exact inherited result suites','seven reachable stages and eighty-one routes','ninety-one rejected mutations','one governor-review handoff followed by successor-version readmission','no support-state or external-effect authority'],'claim_scope':'One finite authored bounded adaptive-generation campaign lifecycle plus two fixed stopped local update campaigns only.','negative_controls':'validator_owned_identity_scope_generation_archive_evaluation_stop_governor_readmission_mutations','negative_control_cases':['campaign, objective, representation, controller, policy, generator, evaluator, qualifier, archive, budget, stop, hazard, consumer, authority, or version substitution','missing scope, denominator, lineage, archive, exposure, qualification, baseline, hazard, cost, stop-effect, residual, handoff, invalidation, or readmission record','budget reset, score-as-admission, useful-improvement inference, candidate authority, release authority, or support authority laundering','wrong stage, replay, support assignment, or external-effect request'],'prohibited_inference':'Does not establish objective legitimacy, evaluator independence, adaptive search quality, semantic novelty, useful improvement, hazard-control efficacy, autonomous discovery, transfer, safe self-improvement, capability, safety, readiness, release, deployment, SOTA, AGI, ASI, or chapter-core support.','contract_precision':'inherited','semantic_review_state':'checked_structured_campaign_governor_lifecycle_not_adaptive_useful_safe_deployed_or_support_authority'})
 req=list(v['required_artifacts'])
 for a in ARTIFACTS:
  if a not in req:req.append(a)
 v['required_artifacts']=req;v['summary']={'required_artifact_count':len(req),'unit_count':len(v['units'])};REGISTRY.write_text(json.dumps(v,indent=2)+'\n');print(f'Registered {SCRIPT}: {len(v["units"])} units, {len(req)} artifacts.')
if __name__=='__main__':main()
