#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; REGISTRY=ROOT/"validation/registry.json"; SCRIPT="validate_institutional_legitimacy_review.py"
ARTIFACTS=["scripts/validate_institutional_legitimacy_review.py","lean/AsiStackProofs/InstitutionalLegitimacyReview.lean","tests/fixtures/proof_models/institutional_legitimacy_dossier.json","evidence_quality/proof_model_dossiers/institutions-international-coordination-and-public-legitimacy.md","chapters/institutions-international-coordination-and-public-legitimacy.qmd","proofs/proof_manifest.json","proofs/proof_triage.json","docs/book_outline.md"]
def main()->None:
 v=json.loads(REGISTRY.read_text()); old=next((r for r in v["units"] if r.get("script")==SCRIPT),None); v["units"]=[r for r in v["units"] if r.get("script")!=SCRIPT]; used={r["order"] for r in v["units"]}; preferred=old.get("order") if old else None; order=preferred if preferred and preferred not in used else next(i for i in range(1,len(v["units"])+2) if i not in used)
 v["units"].append({"id":f"{SCRIPT}:{order}","order":order,"script":SCRIPT,"args":[],"execution_tier":"pr","validation_class":"proof_or_evidence_gate","input_contract":"Canonical institutional-legitimacy Lean review, independent 45-axis fixture, chapter proof boundary, dossier, manifest, triage, and outline binding.","input_artifacts":ARTIFACTS,"output_contract":"Reject lifecycle, exact-repair, evidence-substitution, jurisdiction, affected-public, receipt, collision, consumer, binding, and no-promotion drift.","output_assertions":["eight-transition review reaches only Project Theseus institutional-tabletop eligibility","45/45 admission-axis mutations reject readiness and receive exact repair or refusal dispositions","agreement, law, consultation, conformance, implementation, representation, legitimacy, and authority remain separate","local mandates cannot authorize distinct jurisdictions and finite public inclusion covers every listed public","scope changes invalidate receipts and adverse shortfalls remain adverse","participation cannot recover representation and commitment signals cannot recover effective enforcement","the Governance Rights consumer rejects an incomplete affected-public census","32 exact Lean declarations move no chapter support, release, transfer, or external-effect state"],"claim_scope":"Bounded authored institutional review, evidence-role separation, jurisdiction scope, finite public accounting, receipt invalidation, consumer rejection, and non-identifiability only.","negative_controls":"validator_owned_45_axis_evidence_jurisdiction_public_receipt_collision_consumer_and_binding_mutations","negative_control_cases":["authority laundering","excluded public","treaty theater","stale mandate","forum substitution","legitimacy claim","support promotion"],"prohibited_inference":"Does not establish lawful authority, representativeness, independent review, implementation, enforcement, remedy efficacy, public legitimacy, geopolitical stability, deployment, transfer, SOTA, AGI, or ASI.","contract_precision":"exact","semantic_review_state":"checked_bounded_formal_model_and_independent_consumer_no_support_effect"})
 req=list(v["required_artifacts"])
 for a in ARTIFACTS:
  if a not in req:req.append(a)
 v["units"].sort(key=lambda r:r["order"]);v["required_artifacts"]=req;v["summary"]={"required_artifact_count":len(req),"unit_count":len(v["units"])};REGISTRY.write_text(json.dumps(v,indent=2)+"\n");print(f"Registered {SCRIPT}: {len(v['units'])} units, {len(req)} artifacts.")
if __name__=="__main__":main()
