#!/usr/bin/env python3
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];PATH=ROOT/"validation/registry.json";SCRIPT="validate_deliberation_refinement.py"
ARTIFACTS=["scripts/validate_deliberation_refinement.py","schemas/deliberation_refinement.schema.json","experiments/deliberation_refinement/results/2026-07-15-local.json","docs/deliberation_refinement.md","evidence_quality/model_adequacy_dossiers/deliberation-refinement.md","lean/AsiStackProofs/DeliberationRefinement.lean","scripts/validate_deliberation_admission.py","scripts/validate_post_v2_routing_deliberation.py","scripts/validate_post_v2_1_outcomes.py","experiments/post_v2_1_evidence_program/p2/results/test.json","experiments/post_v2_1_evidence_program/results/2026-07-11-post-v2-1-outcomes.json"]
r=json.loads(PATH.read_text());r["units"]=[u for u in r["units"] if u.get("script")!=SCRIPT];order=len(r["units"])+1
r["units"].append({"id":f"{SCRIPT}:{order}","order":order,"script":SCRIPT,"args":[],"execution_tier":"deep","validation_class":"proof_or_evidence_gate","input_contract":"Reachable governed-deliberation lifecycle, exact admission, post-v2 synthetic, and post-v2.1 actual-model results, independent route consumer, schema, receipt, and adequacy dossier.","input_artifacts":ARTIFACTS,"output_contract":"Reject identity, scope, candidate-custody, evaluator, corruption/repair/faithfulness, cost, selection, stop, residual, handoff, support, and effect failures.","output_assertions":["eight reachable stages","59 routes","51 rejected non-accepting mutations","four SHA-256-bound source artifacts across three source families","actual-model 0/60 no-change boundary","support and external effect none"],"claim_scope":"One finite authored request-to-closure policy, two bounded synthetic result families, and one failed actual-model attempt.","negative_controls":"validator_owned_deliberation_route_mutations","negative_control_cases":["identity, policy, evaluator, or result substitution","missing candidate history, verifier boundary, corruption/repair/faithfulness, cost, stop, or residual","raw-score, execution-authority, support, or effect laundering"],"prohibited_inference":"No useful language-model reasoning, natural-workload utility, verifier adequacy, trace faithfulness, calibrated routing/abstention, execution, safety, transfer, SOTA, AGI, ASI, or support.","contract_precision":"inherited","semantic_review_state":"checked_request_to_closure_lifecycle_and_failed_actual_model_attempt_not_empirical_benefit_or_support_authority"})
required=list(r["required_artifacts"])
for a in ARTIFACTS:
 if a not in required:required.append(a)
r["required_artifacts"]=required;r["summary"]={"required_artifact_count":len(required),"unit_count":len(r["units"])};PATH.write_text(json.dumps(r,indent=2)+"\n");print(f"Registered {SCRIPT}: {len(r['units'])} units, {len(required)} artifacts.")
