#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REGISTRY=ROOT/'validation/registry.json';SCRIPT='validate_scalable_oversight_refinement.py'
ARTIFACTS=['scripts/validate_scalable_oversight_refinement.py','schemas/scalable_oversight_refinement.schema.json','experiments/scalable_oversight_refinement/results/2026-07-15-local.json','docs/scalable_oversight_refinement.md','evidence_quality/model_adequacy_dossiers/scalable-oversight-refinement.md','lean/AsiStackProofs/ScalableOversightRefinement.lean','scripts/validate_scalable_oversight_protocol.py','experiments/scalable_oversight_protocol/fixtures/cases.json','experiments/scalable_oversight_protocol/results/2026-07-13-local.json']
def main():
 v=json.loads(REGISTRY.read_text());v['units']=[u for u in v['units'] if u.get('script')!=SCRIPT];order=len(v['units'])+1
 v['units'].append({'id':f'{SCRIPT}:{order}','order':order,'script':SCRIPT,'args':[],'execution_tier':'deep','validation_class':'proof_or_evidence_gate','input_contract':'Reachable Lean oversight-review lifecycle, exact inherited seven-case suite, independent consumer, result schema, receipt, and model-adequacy dossier.','input_artifacts':ARTIFACTS,'output_contract':'Reject identity substitution, incomplete scope/protocol/review/audit/adjudication/handoff/readmission custody, replay, competence or authority laundering, and support/effect leakage.','output_assertions':['seven exact inherited cases','fifty-eight routes and seven reachable stages','sixty-five rejected mutations','bounded-use handoff followed by successor-version readmission','no support-state or external-effect authority'],'claim_scope':'One finite authored oversight-review record lifecycle plus the existing seven-case fixture only.','negative_controls':'validator_owned_identity_scope_protocol_review_audit_abstention_readmission_authority_mutations','negative_control_cases':['task, consumer, protocol, cohort, system, supervisor, evidence-view, dependency, baseline, auditor, policy, residual, authority, or version substitution','missing scope, envelope, access, incentive, cohort, failure, expiry, review, disagreement, denominator, coverage, abstention, cost, audit, separation, dependency, correlation, outcome, failure, uncertainty, residual, disposition, escalation, consumer, binding, or handoff record','incomplete invalidation, ordinary-route blocking, or successor version','wrong stage, replay, competence inference, policy/release authority laundering, support assignment, or external-effect request'],'prohibited_inference':'Does not establish reviewer competence, independence, calibration, outcome truth, debate, consultancy, weak-to-strong efficacy, causal usefulness, safety, readiness, release authority, deployed invalidation, transfer, AGI, ASI, or chapter-core support.','contract_precision':'inherited','semantic_review_state':'checked_structured_oversight_review_lifecycle_not_competence_empirical_deployed_or_support_authority'})
 req=list(v['required_artifacts'])
 for a in ARTIFACTS:
  if a not in req:req.append(a)
 v['required_artifacts']=req;v['summary']={'required_artifact_count':len(req),'unit_count':len(v['units'])};REGISTRY.write_text(json.dumps(v,indent=2)+'\n');print(f'Registered {SCRIPT}: {len(v["units"])} units, {len(req)} artifacts.')
if __name__=='__main__':main()
