#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; REGISTRY=ROOT/"validation/registry.json"; SCRIPT="validate_p4_m8_kerc_campaign.py"
ARTIFACTS=["scripts/p4_m8_kerc_common.py","scripts/build_p4_m8_kerc_campaign.py","scripts/run_p4_m8_kerc_campaign.py","scripts/validate_p4_m8_kerc_design.py","scripts/validate_p4_m8_kerc_campaign.py","schemas/p4_m8_kerc_result.schema.json","experiments/p4_kerc_runtime/corpus.json","experiments/p4_kerc_runtime/design.json","experiments/p4_kerc_runtime/preregistration.json","experiments/p4_kerc_runtime/raw/campaign_run.json","experiments/p4_kerc_runtime/results/confirmatory_result.json","docs/p4_kerc_runtime_campaign.md","evidence_transitions/post_v2_3/kerc_protected_exact_handle_synthetic_test_backed.json","evidence_transitions/post_v2_3/kerc_shared_glossary_break_even_synthetic_test_backed.json","evidence_transitions/post_v2_3/kerc_broad_efficiency_refuted.json"]
def main():
 value=json.loads(REGISTRY.read_text()); existing=next((x for x in value["units"] if x.get("script")==SCRIPT),None); value["units"]=[x for x in value["units"] if x.get("script")!=SCRIPT]; used={x["order"] for x in value["units"]}; preferred=existing.get("order") if existing else None; order=preferred if preferred and preferred not in used else next(i for i in range(1,len(value["units"])+2) if i not in used)
 value["units"].append({"id":f"{SCRIPT}:{order}","order":order,"script":SCRIPT,"args":[],"execution_tier":"pr","validation_class":"proof_or_evidence_gate","input_contract":"One prospectively frozen 192-record bilingual KERC runtime campaign with 64 heldout records, five seeds, eight baseline families, thirteen ablations, twenty attacks, and three progressively honest slices.","input_artifacts":ARTIFACTS,"output_contract":"Preserve the broad matched-efficiency refutation, two bounded finite transitions, one escaped attack, complete-rate accounting, failed new-chapter gate, and zero chapter-core movement.","output_assertions":["192/128/64 denominators remain exact","all compared core accuracies remain 0.5","714.0-byte packet and 73.25-byte best-simple rates remain visible","19/20 attacks and quote escape remain visible","two bounded upward claims and one exact refutation remain exact","no chapter core or new chapter moves"],"claim_scope":"One authored bilingual templated corpus, deterministic compiler, and small linear cores only.","negative_controls":"validator_owned_ten_kerc_laundering_mutations","negative_control_cases":["denominator inflation","broad-success laundering","attack erasure","core-score rewrite","packet-cost erasure","new-chapter invention","support widening","chapter-core transition","new chapter transition","refutation reversal"],"prohibited_inference":"No general semantic truth, independent verifier validity, security, multilingual fairness, model/domain transfer, production or energy efficiency, SOTA, AGI, ASI, deployment, publication, release, or chapter-core support.","contract_precision":"exact","semantic_review_state":"checked_broad_refutation_two_bounded_finite_transitions_and_scope_ceiling"})
 design_script="validate_p4_m8_kerc_design.py"; value["units"]=[x for x in value["units"] if x.get("script")!=design_script]; used={x["order"] for x in value["units"]}; design_order=next(i for i in range(1,len(value["units"])+2) if i not in used)
 value["units"].append({"id":f"{design_script}:{design_order}","order":design_order,"script":design_script,"args":[],"execution_tier":"pr","validation_class":"schema_or_structure","input_contract":"Prospectively frozen KERC design, corpus, schema, and executable digests.","input_artifacts":["scripts/validate_p4_m8_kerc_design.py","experiments/p4_kerc_runtime/design.json","experiments/p4_kerc_runtime/corpus.json","experiments/p4_kerc_runtime/preregistration.json"],"output_contract":"Recheck the immutable 192-row design, exact split, baseline/ablation/attack denominators, label isolation, retry prohibition, and six mutations.","output_assertions":["192 records and 128/32/32 split","eight baselines, thirteen ablations, twenty attacks","prospective hashes and no retry remain exact","six mutations reject"],"claim_scope":"Campaign design integrity only.","negative_controls":"validator_owned_six_design_mutations","negative_control_cases":["denominator inflation","baseline deletion","retry opening","label leakage","attack deletion","ceiling weakening"],"prohibited_inference":"No outcome, support, semantic, efficiency, security, publication, or release effect.","contract_precision":"exact","semantic_review_state":"checked_prospective_design_integrity"})
 req=list(value["required_artifacts"])
 for x in ARTIFACTS:
  if x not in req:req.append(x)
 value["units"].sort(key=lambda x:x["order"]); value["required_artifacts"]=req; value["summary"]={"required_artifact_count":len(req),"unit_count":len(value["units"])}; REGISTRY.write_text(json.dumps(value,indent=2)+"\n"); print(f"Registered {SCRIPT}: {len(value['units'])} units, {len(req)} artifacts.")
if __name__=="__main__":main()
