#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REGISTRY=ROOT/'validation/registry.json';SCRIPT='validate_readiness_refinement.py'
ARTIFACTS=['scripts/validate_readiness_refinement.py','schemas/readiness_refinement.schema.json','experiments/readiness_refinement/results/2026-07-15-local.json','docs/readiness_refinement.md','evidence_quality/model_adequacy_dossiers/readiness-refinement.md','lean/AsiStackProofs/ReadinessRefinement.lean','scripts/validate_readiness_residual_gates.py','scripts/validate_readiness_lifecycle_probe.py','scripts/validate_readiness_check_lifecycle.py']
def main():
 v=json.loads(REGISTRY.read_text());v['units']=[u for u in v['units'] if u.get('script')!=SCRIPT];order=len(v['units'])+1
 v['units'].append({'id':f'{SCRIPT}:{order}','order':order,'script':SCRIPT,'args':[],'execution_tier':'deep','validation_class':'proof_or_evidence_gate','input_contract':'Reachable Lean readiness lifecycle, three exact bounded suites, independent consumer, result schema, receipt, and model-adequacy dossier.','input_artifacts':ARTIFACTS,'output_contract':'Reject identity substitution, incomplete evidence, regression, missing residual/fallback/rollback/monitoring/outcome/independence/transfer, incomplete quarantine and terminal custody, replay, and support/effect leakage.','output_assertions':['three exact bounded suites','forty routes and seven reachable stages','forty-five rejected mutations','separate ordinary release, quarantine, and terminal closure','no support-state or external-effect authority'],'claim_scope':'One finite authored readiness lifecycle plus three existing bounded suites only.','negative_controls':'validator_owned_identity_evidence_lifecycle_quarantine_terminal_authority_mutations','negative_control_cases':['capability, implementation, state, workload, baseline, evaluator, policy, authority, consumer, fallback, residual, or event substitution','missing gate, regression, residual, fallback, rollback, monitoring, outcome, independence, transfer, or delayed evidence','incomplete quarantine propagation, ordinary-route blocking, diagnostics, dependency, revocation, receipt, or acknowledgment','support assignment or external-effect authority leak'],'prohibited_inference':'Does not establish evidence truth, evaluator adequacy, gate calibration, natural usefulness, effect-complete rollback, deployed quarantine or revocation, transfer, safety, SOTA, AGI, ASI, or chapter-core support.','contract_precision':'inherited','semantic_review_state':'checked_structured_candidate_terminal_readiness_lifecycle_not_natural_deployed_or_support_authority'})
 req=list(v['required_artifacts'])
 for a in ARTIFACTS:
  if a not in req:req.append(a)
 v['required_artifacts']=req;v['summary']={'required_artifact_count':len(req),'unit_count':len(v['units'])};REGISTRY.write_text(json.dumps(v,indent=2)+'\n');print(f'Registered {SCRIPT}: {len(v["units"])} units, {len(req)} artifacts.')
if __name__=='__main__':main()
