#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shlex
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "experiments" / "phase5_harness_registry.json"
REPORT = ROOT / "docs" / "phase5_harness_runner.md"


@dataclass(frozen=True)
class HarnessResult:
    harness_id: str
    command: str
    result_summary: str
    result_record: str
    returncode: int
    output: str
    summary_matched: bool


def read_json(path: Path) -> Any:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def qmd_escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def load_registry() -> list[dict[str, Any]]:
    registry = read_json(REGISTRY)
    if not isinstance(registry, list):
        raise TypeError("experiments/phase5_harness_registry.json must contain a list.")
    rows: list[dict[str, Any]] = []
    for index, row in enumerate(registry):
        if not isinstance(row, dict):
            raise TypeError(f"phase5_harness_registry[{index}] must be an object.")
        for field in ("id", "command", "result_summary", "result_record"):
            if not isinstance(row.get(field), str) or not row[field].strip():
                raise TypeError(f"{row.get('id', index)!r}: missing non-empty {field}.")
        rows.append(row)
    return rows


def run_harness(row: dict[str, Any]) -> HarnessResult:
    command = str(row["command"])
    result = subprocess.run(
        shlex.split(command),
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    output = result.stdout.strip()
    expected_summary = str(row["result_summary"]).strip()
    return HarnessResult(
        harness_id=str(row["id"]),
        command=command,
        result_summary=expected_summary,
        result_record=str(row["result_record"]),
        returncode=result.returncode,
        output=output,
        summary_matched=expected_summary in output,
    )


def build_report(results: list[HarnessResult]) -> str:
    passed = [result for result in results if result.returncode == 0 and result.summary_matched]
    rows = [
        f"| `{qmd_escape(result.harness_id)}` | `{qmd_escape(result.command)}` | "
        f"{'pass' if result.returncode == 0 else 'fail'} | "
        f"{'yes' if result.summary_matched else 'no'} | "
        f"`{qmd_escape(result.result_record)}` | {qmd_escape(result.output)} |"
        for result in results
    ]
    return f"""# Phase 5 Harness Runner

Generated by `python3 scripts/run_phase5_harnesses.py --write-report`.

This report records a registry-driven local execution of the Phase 5 harness suite. The runner loads `experiments/phase5_harness_registry.json`, executes each registered command, and checks that each command output contains the registry `result_summary`.

This is a synthetic-harness execution record. It does **not** promote Appendix C support states, prove deployed runtime behavior, prove model quality, establish benchmark performance, or create empirical evidence beyond the named deterministic fixture checks.

## Summary

| Metric | Value |
|---|---:|
| Registered harnesses run | {len(results)} |
| Harnesses passing return code and summary check | {len(passed)} |
| Harnesses requiring attention | {len(results) - len(passed)} |

## Results

| Harness | Command | Return code | Summary matched | Result record | Output |
|---|---|---|---|---|---|
{chr(10).join(rows)}
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--only", action="append", default=[], help="Run only a registry id; may be repeated.")
    parser.add_argument("--list", action="store_true", help="List registry ids and exit.")
    parser.add_argument("--write-report", action="store_true", help="Write docs/phase5_harness_runner.md after running.")
    args = parser.parse_args()

    try:
        registry = load_registry()
    except Exception as exc:
        print(f"Phase 5 harness runner failed: {exc}")
        sys.exit(1)

    if args.list:
        for row in registry:
            print(row["id"])
        return

    if args.only:
        wanted = set(args.only)
        registry = [row for row in registry if row["id"] in wanted]
        missing = sorted(wanted - {row["id"] for row in registry})
        if missing:
            print("Unknown Phase 5 harness id(s): " + ", ".join(missing))
            sys.exit(1)

    results = [run_harness(row) for row in registry]
    if args.write_report:
        REPORT.write_text(build_report(results), encoding="utf-8")

    failures = [
        result for result in results if result.returncode != 0 or not result.summary_matched
    ]
    for result in results:
        print(f"[{result.harness_id}] {result.output}")

    if failures:
        print("Phase 5 harness runner failed:")
        for result in failures:
            reason = []
            if result.returncode != 0:
                reason.append(f"return code {result.returncode}")
            if not result.summary_matched:
                reason.append("registry summary not found in output")
            print(f" - {result.harness_id}: {', '.join(reason)}")
        sys.exit(1)

    print(f"Phase 5 harness runner passed: {len(results)} registered harness(es).")


if __name__ == "__main__":
    main()
