#!/usr/bin/env python3
"""Validate generated raster key-figure artifacts without approving final art.

The observed pass inspects ignored local PNG fallbacks generated by
`scripts/render_curated_reader_formats.py`. The normal validation pass checks
the tracked manifest and review doc so CI does not depend on ignored build
outputs or local raster libraries.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
READER_MANIFEST = ROOT / "editions" / "reader_manuscript" / "v1_0" / "manifest.json"
PNG_DIR = ROOT / "build" / "curated_reader_edition" / "assets" / "diagrams" / "format-png"
RESULT = ROOT / "editions" / "reader_manuscript" / "v1_0" / "key_figure_raster_manifest.json"
DOC = ROOT / "docs" / "reader_key_figure_raster_review.md"
COMMAND = "python3 scripts/validate_reader_key_figure_raster_probe.py"
EXPECTED_COUNT = 10
EXPECTED_DIMENSIONS = (1200, 760)


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def fail(errors: list[str]) -> None:
    print("Reader key-figure raster probe validation failed:")
    for error in errors:
        print(f" - {error}")
    sys.exit(1)


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def key_figures() -> list[dict[str, Any]]:
    manifest = load_json(READER_MANIFEST)
    figures = manifest.get("reader_handoff_contract", {}).get("key_figure_targets", [])
    if not isinstance(figures, list) or len(figures) != EXPECTED_COUNT:
        fail(["reader_handoff_contract.key_figure_targets must contain exactly 10 records."])
    rows: list[dict[str, Any]] = []
    for figure in figures:
        if not isinstance(figure, dict):
            fail(["key_figure_targets entries must be objects."])
        asset = str(figure.get("draft_asset_path", ""))
        stem = Path(asset).stem
        if not stem:
            fail([f"key figure target missing draft_asset_path: {figure!r}"])
        rows.append(
            {
                "id": figure.get("id"),
                "draft_asset_path": asset,
                "raster_artifact": str(Path("build/curated_reader_edition/assets/diagrams/format-png") / f"{stem}.png"),
                "stem": stem,
            }
        )
    return rows


def inspect_png(row: dict[str, Any]) -> dict[str, Any]:
    try:
        from PIL import Image
    except ImportError as exc:  # pragma: no cover - depends on local environment.
        fail([f"Pillow is required for --write-manifest raster inspection: {exc}"])

    path = ROOT / str(row["raster_artifact"])
    if not path.exists():
        fail([f"missing raster key-figure artifact: {rel(path)}"])

    image = Image.open(path).convert("RGBA")
    width, height = image.size
    pixels = list(image.getdata())
    opaque_count = 0
    dark_count = 0
    mid_tone_count = 0
    luminance_sum = 0.0
    luminance_sq_sum = 0.0
    min_luminance = 255.0
    max_luminance = 0.0
    quantized_colors: set[tuple[int, int, int]] = set()
    for r, g, b, a in pixels:
        if a <= 0:
            continue
        opaque_count += 1
        luminance = 0.2126 * r + 0.7152 * g + 0.0722 * b
        luminance_sum += luminance
        luminance_sq_sum += luminance * luminance
        min_luminance = min(min_luminance, luminance)
        max_luminance = max(max_luminance, luminance)
        if luminance < 80:
            dark_count += 1
        if luminance < 220:
            mid_tone_count += 1
        quantized_colors.add((r // 16, g // 16, b // 16))

    total_pixels = width * height
    if opaque_count == 0:
        fail([f"{rel(path)} has no nontransparent pixels."])
    mean_luminance = luminance_sum / opaque_count
    variance = max(0.0, luminance_sq_sum / opaque_count - mean_luminance * mean_luminance)
    luminance_std = math.sqrt(variance)
    edge_alpha_values = []
    for x in range(width):
        edge_alpha_values.append(image.getpixel((x, 0))[3])
        edge_alpha_values.append(image.getpixel((x, height - 1))[3])
    for y in range(height):
        edge_alpha_values.append(image.getpixel((0, y))[3])
        edge_alpha_values.append(image.getpixel((width - 1, y))[3])
    edge_opaque_percent = 100.0 * sum(1 for value in edge_alpha_values if value > 0) / len(edge_alpha_values)

    return {
        **row,
        "artifact_exists": True,
        "sha256": sha256_file(path),
        "bytes": path.stat().st_size,
        "width": width,
        "height": height,
        "standard_dimensions": [width, height] == list(EXPECTED_DIMENSIONS),
        "opaque_pixel_percent": round(100.0 * opaque_count / total_pixels, 3),
        "transparent_pixel_count": total_pixels - opaque_count,
        "edge_opaque_percent": round(edge_opaque_percent, 2),
        "mean_luminance": round(mean_luminance, 2),
        "luminance_std": round(luminance_std, 2),
        "min_luminance": round(min_luminance, 2),
        "max_luminance": round(max_luminance, 2),
        "dark_pixel_percent": round(100.0 * dark_count / opaque_count, 2),
        "mid_tone_pixel_percent": round(100.0 * mid_tone_count / opaque_count, 2),
        "quantized_color_count": len(quantized_colors),
        "passed": (
            [width, height] == list(EXPECTED_DIMENSIONS)
            and opaque_count / total_pixels >= 0.999
            and luminance_std >= 25.0
            and len(quantized_colors) >= 100
            and dark_count / opaque_count >= 0.004
            and mid_tone_count / opaque_count >= 0.05
            and min_luminance <= 40.0
            and max_luminance >= 250.0
        ),
    }


def observe() -> dict[str, Any]:
    figures = key_figures()
    rows = [inspect_png(row) for row in figures]
    summary = {
        "figure_count": len(rows),
        "raster_artifact_count": sum(1 for row in rows if row.get("artifact_exists") is True),
        "standard_dimension_count": sum(1 for row in rows if row.get("standard_dimensions") is True),
        "minimum_opaque_pixel_percent": min((row["opaque_pixel_percent"] for row in rows), default=0),
        "minimum_luminance_std": min((row["luminance_std"] for row in rows), default=0),
        "minimum_quantized_color_count": min((row["quantized_color_count"] for row in rows), default=0),
        "minimum_dark_pixel_percent": min((row["dark_pixel_percent"] for row in rows), default=0),
        "minimum_mid_tone_pixel_percent": min((row["mid_tone_pixel_percent"] for row in rows), default=0),
        "maximum_transparent_pixel_count": max((row["transparent_pixel_count"] for row in rows), default=0),
        "minimum_edge_opaque_percent": min((row["edge_opaque_percent"] for row in rows), default=0),
        "total_raster_bytes": sum(int(row["bytes"]) for row in rows),
    }
    return {
        "schema_version": "asi_stack.reader_key_figure_raster_probe.v0",
        "status": "passed_local_raster_artifact_probe",
        "command": COMMAND,
        "source_manifest": rel(READER_MANIFEST),
        "raster_source_root": rel(PNG_DIR),
        "summary": summary,
        "figures": rows,
        "release_blockers_preserved": [
            "final_figure_artifact_review_not_completed",
            "manual_aesthetic_review_not_completed",
            "epub_e_reader_review_not_completed",
            "docx_application_review_not_completed",
            "pdf_page_layout_review_not_completed",
            "reader_edition_release_record_not_created",
        ],
        "non_claims": [
            "This is an automated local PNG raster artifact smoke review only.",
            "This probe is not final figure-artifact approval.",
            "This probe is not manual aesthetic review, not e-reader visual review, not DOCX/PDF application review, and not reader release approval.",
            "This probe does not prove visual quality, accessibility adequacy, narration quality, model behavior, deployed runtime behavior, evidence transitions, or support-state promotion.",
        ],
    }


def validate_result(result: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    if result.get("schema_version") != "asi_stack.reader_key_figure_raster_probe.v0":
        errors.append("schema_version must be asi_stack.reader_key_figure_raster_probe.v0.")
    if result.get("status") != "passed_local_raster_artifact_probe":
        errors.append("status must be passed_local_raster_artifact_probe.")
    if result.get("source_manifest") != rel(READER_MANIFEST):
        errors.append("source_manifest drifted.")
    if result.get("raster_source_root") != rel(PNG_DIR):
        errors.append("raster_source_root drifted.")
    summary = result.get("summary", {})
    if not isinstance(summary, dict):
        errors.append("summary must be an object.")
        summary = {}
    expected_summary = {
        "figure_count": 10,
        "raster_artifact_count": 10,
        "standard_dimension_count": 10,
        "maximum_transparent_pixel_count": 420,
    }
    for key, expected in expected_summary.items():
        if summary.get(key) != expected:
            errors.append(f"summary.{key} must be {expected!r}; found {summary.get(key)!r}.")
    threshold_summary = {
        "minimum_opaque_pixel_percent": 99.9,
        "minimum_luminance_std": 25.0,
        "minimum_quantized_color_count": 100,
        "minimum_dark_pixel_percent": 0.4,
        "minimum_mid_tone_pixel_percent": 5.0,
        "minimum_edge_opaque_percent": 96.0,
    }
    for key, minimum in threshold_summary.items():
        observed = summary.get(key)
        if not isinstance(observed, (int, float)) or observed < minimum:
            errors.append(f"summary.{key} must be at least {minimum}; found {observed!r}.")

    figures = result.get("figures", [])
    if not isinstance(figures, list) or len(figures) != EXPECTED_COUNT:
        errors.append("figures must contain 10 rows.")
        figures = []
    seen: set[str] = set()
    for row in figures:
        if not isinstance(row, dict):
            errors.append("figure rows must be objects.")
            continue
        figure_id = row.get("id")
        if not isinstance(figure_id, str) or not figure_id:
            errors.append("figure row missing id.")
        elif figure_id in seen:
            errors.append(f"duplicate figure id {figure_id}.")
        else:
            seen.add(figure_id)
        if row.get("passed") is not True:
            errors.append(f"{figure_id}: raster row must pass.")
        if [row.get("width"), row.get("height")] != list(EXPECTED_DIMENSIONS):
            errors.append(f"{figure_id}: raster dimensions must be 1200 x 760.")
        if int(row.get("quantized_color_count", 0)) < 100:
            errors.append(f"{figure_id}: quantized_color_count too low.")
        sha = str(row.get("sha256", ""))
        if not re_fullmatch_sha256(sha):
            errors.append(f"{figure_id}: sha256 must be a 64-char hex digest.")
    blockers = set(result.get("release_blockers_preserved", []))
    for blocker in (
        "final_figure_artifact_review_not_completed",
        "manual_aesthetic_review_not_completed",
        "epub_e_reader_review_not_completed",
        "docx_application_review_not_completed",
        "pdf_page_layout_review_not_completed",
        "reader_edition_release_record_not_created",
    ):
        if blocker not in blockers:
            errors.append(f"release_blockers_preserved missing {blocker}.")
    non_claim_text = " ".join(str(item) for item in result.get("non_claims", [])).lower()
    for phrase in ("automated local png", "not final figure-artifact approval", "not manual aesthetic review", "not reader release approval", "does not prove visual quality"):
        if phrase not in non_claim_text:
            errors.append(f"non_claims missing boundary phrase: {phrase}")
    return errors


def re_fullmatch_sha256(value: str) -> bool:
    if len(value) != 64:
        return False
    return all(char in "0123456789abcdef" for char in value)


def write_doc(result: dict[str, Any]) -> None:
    summary = result["summary"]
    lines = [
        "# Reader Key-Figure Raster Review",
        "",
        "Last checked: 2026-07-04",
        "",
        "Command:",
        "",
        "```bash",
        f"{COMMAND} --write-manifest --write-doc",
        "```",
        "",
        "This automated review inspects the current ignored PNG raster artifacts generated for the curated reader figure fallbacks. It checks that all ten key figures rasterized to the expected 1200 x 760 canvas, are not blank or low-ink, preserve visual variation, and retain opaque page-area coverage. It is not manual aesthetic review, not final figure-artifact approval, not e-reader review, not DOCX/PDF application review, and not reader release approval.",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Status | `{result['status']}` |",
        f"| Raster artifacts checked | {summary['raster_artifact_count']} |",
        f"| Standard dimensions | {summary['standard_dimension_count']} |",
        f"| Minimum opaque pixel coverage | {summary['minimum_opaque_pixel_percent']}% |",
        f"| Minimum luminance standard deviation | {summary['minimum_luminance_std']} |",
        f"| Minimum quantized color count | {summary['minimum_quantized_color_count']} |",
        f"| Minimum dark-pixel share | {summary['minimum_dark_pixel_percent']}% |",
        f"| Minimum mid-tone share | {summary['minimum_mid_tone_pixel_percent']}% |",
        f"| Maximum transparent pixels | {summary['maximum_transparent_pixel_count']} |",
        f"| Minimum edge opaque coverage | {summary['minimum_edge_opaque_percent']}% |",
        f"| Total raster bytes | {summary['total_raster_bytes']} |",
        "",
        "## Per-Figure Raster Rows",
        "",
        "| Figure | Raster artifact | Size | Luminance std | Quantized colors | SHA-256 |",
        "|---|---|---:|---:|---:|---|",
    ]
    for row in result["figures"]:
        lines.append(
            f"| `{row['id']}` | `{row['raster_artifact']}` | {row['width']} x {row['height']} | {row['luminance_std']} | {row['quantized_color_count']} | `{row['sha256']}` |"
        )
    lines.extend(
        [
            "",
            "## Residuals",
            "",
            "- This automated raster review catches missing, blank, low-ink, or visually collapsed PNG fallbacks.",
            "- It does not judge whether the figure is beautiful, editorially final, or optimal for a particular reader.",
            "- EPUB still needs real e-reader review, DOCX still needs application review, and PDF still needs page-level layout review.",
            "- Final figure-artifact approval and reader release approval still require an edition release record naming exact reviewed artifacts.",
            "",
        ]
    )
    DOC.write_text("\n".join(lines), encoding="utf-8")


def validate_doc(errors: list[str]) -> None:
    if not DOC.exists():
        errors.append(f"{rel(DOC)} is missing.")
        return
    text = DOC.read_text(encoding="utf-8")
    required = [
        "Reader Key-Figure Raster Review",
        f"{COMMAND} --write-manifest --write-doc",
        "| Raster artifacts checked | 10 |",
        "| Standard dimensions | 10 |",
        "Minimum luminance standard deviation",
        "Minimum quantized color count",
        "not manual aesthetic review",
        "not final figure-artifact approval",
        "not reader release approval",
        "Final figure-artifact approval and reader release approval still require an edition release record",
    ]
    for fragment in required:
        if fragment not in text:
            errors.append(f"{rel(DOC)} missing required fragment: {fragment}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-manifest", action="store_true", help="inspect local PNG artifacts and write the tracked manifest")
    parser.add_argument("--write-doc", action="store_true", help="rewrite the tracked markdown review doc")
    args = parser.parse_args()

    if args.write_manifest:
        result = observe()
        errors = validate_result(result)
        if errors:
            fail(errors)
        RESULT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    else:
        if not RESULT.exists():
            fail([f"{rel(RESULT)} is missing; run with --write-manifest."])
        result = load_json(RESULT)

    errors = validate_result(result)
    if args.write_doc:
        write_doc(result)
    validate_doc(errors)
    if errors:
        fail(errors)
    print(
        "Reader key-figure raster probe validation passed: "
        f"{result['summary']['raster_artifact_count']} PNG artifacts, "
        f"minimum luminance std {result['summary']['minimum_luminance_std']}."
    )


if __name__ == "__main__":
    main()
