#!/usr/bin/env python3
"""Validate the chapter-level external-grounding status ledger."""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs" / "chapter_external_grounding_status.md"
BUILDER = ROOT / "scripts" / "build_chapter_external_grounding_status.py"
ROW_RE = re.compile(r"^\|\s*([^|]+)\|\s*`([^`]+)`\s*\|\s*([^|]+)\|\s*`([^`]+)`\s*\|")

EXPECTED_COUNTS = {
    "source-noted": 50,
    "explicit_exception": 4,
    "candidate_backlog": 0,
    "missing": 0,
}

REQUIRED_STRINGS = [
    "Generated by `python3 scripts/build_chapter_external_grounding_status.py`.",
    "Corben/local sources to mine first",
    "Do not treat this ledger as source-derived support",
    "does not promote any chapter core claim above `argument`",
    "does not claim exhaustive literature coverage",
    "does not reproduce, verify, or accept any external result",
]

FORBIDDEN_STRINGS = [
    "marks the chapter as external-literature-backed",
    "source-derived support is complete",
    "validated by external literature",
    "proves the chapter",
    "reproduced benchmark evidence exists",
    "v1.x evidence release approved",
]


def load_builder() -> Any:
    spec = importlib.util.spec_from_file_location("chapter_external_grounding_builder", BUILDER)
    if spec is None or spec.loader is None:
        raise SystemExit("Unable to load build_chapter_external_grounding_status.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def fail(errors: list[str]) -> None:
    print("Chapter external grounding status validation failed:")
    for error in errors:
        print(f" - {error}")
    sys.exit(1)


def main() -> None:
    builder = load_builder()
    rows = builder.build_rows()
    expected = builder.render_report(rows)
    errors: list[str] = []

    if not REPORT.exists():
        errors.append("docs/chapter_external_grounding_status.md is missing.")
        fail(errors)

    text = REPORT.read_text(encoding="utf-8", errors="ignore")
    if text != expected:
        errors.append("docs/chapter_external_grounding_status.md is stale; run build script.")

    row_by_id = {str(row["chapter_id"]): row for row in rows}
    if len(row_by_id) != len(rows):
        errors.append("Generated grounding rows contain duplicate chapter IDs.")

    counts: dict[str, int] = {}
    for row in rows:
        status = str(row["grounding_status"])
        counts[status] = counts.get(status, 0) + 1
        chapter_id = str(row["chapter_id"])
        external_ids = row.get("external_ids", [])
        corben_ids = row.get("corben_ids", [])
        audit_status = str(row.get("audit_status", ""))
        if status == "source-noted" and not external_ids:
            errors.append(f"{chapter_id}: source-noted row has no external IDs.")
        if status == "explicit_exception" and audit_status != "exception_recorded":
            errors.append(f"{chapter_id}: explicit exception does not match external-SOTA audit.")
        if status == "candidate_backlog":
            errors.append(f"{chapter_id}: candidate backlog still open.")
        if status == "missing":
            errors.append(f"{chapter_id}: missing from external-SOTA audit.")
        if not corben_ids:
            errors.append(f"{chapter_id}: no Corben/local source mining queue is recorded.")

    for status, expected_count in EXPECTED_COUNTS.items():
        actual = counts.get(status, 0)
        if actual != expected_count:
            errors.append(f"{status}: expected {expected_count}, found {actual}.")

    report_rows = {
        match.group(2): match.group(4)
        for line in text.splitlines()
        if (match := ROW_RE.match(line))
    }
    if set(report_rows) != set(row_by_id):
        missing_in_report = sorted(set(row_by_id) - set(report_rows))
        extra_in_report = sorted(set(report_rows) - set(row_by_id))
        if missing_in_report:
            errors.append(f"Report is missing chapter rows: {missing_in_report}")
        if extra_in_report:
            errors.append(f"Report has unknown chapter rows: {extra_in_report}")

    for needle in REQUIRED_STRINGS:
        if needle not in text:
            errors.append(f"Report missing required boundary text: {needle}")
    lowered = text.lower()
    for forbidden in FORBIDDEN_STRINGS:
        if forbidden.lower() in lowered:
            errors.append(f"Report contains forbidden overclaim text: {forbidden}")

    public_refs = {
        "README.md": "docs/chapter_external_grounding_status.md",
        "docs/repository_map.md": "docs/chapter_external_grounding_status.md",
        "docs/publication_readiness.md": "docs/chapter_external_grounding_status.md",
    }
    for path, needle in public_refs.items():
        surface = (ROOT / path).read_text(encoding="utf-8", errors="ignore")
        if needle not in surface:
            errors.append(f"{path} does not reference {needle}.")

    if errors:
        fail(errors)

    print(
        "Chapter external grounding status validation passed: "
        f"{len(rows)} chapters, "
        f"{counts.get('source-noted', 0)} source-noted, "
        f"{counts.get('explicit_exception', 0)} explicit exception(s), "
        f"{counts.get('candidate_backlog', 0)} backlog row(s)."
    )


if __name__ == "__main__":
    main()
