#!/usr/bin/env python3
"""Validate the generated source-ownership appendices.

Appendix G is reserved for Corben's supplied/authored source corpus.
Appendix H is reserved for third-party external literature. The split is
generated by `scripts/sync_scaffold.py` from `sources/source_inventory.json`;
this guard makes that ownership boundary explicit in CI.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ROOT / "sources" / "source_inventory.json"
APPENDIX_G = ROOT / "appendices" / "G_bibliography.qmd"
APPENDIX_H = ROOT / "appendices" / "H_external_literature.qmd"
ROW_ID_RE = re.compile(r"^\|\s*`([^`]+)`\s*\|", re.MULTILINE)


def fail(errors: list[str]) -> None:
    print("Source appendix ownership validation failed:")
    for error in errors:
        print(f" - {error}")
    sys.exit(1)


def load_records() -> list[dict]:
    records = json.loads(INVENTORY.read_text(encoding="utf-8"))
    if not isinstance(records, list):
        fail(["sources/source_inventory.json must contain a list."])
    bad = [index for index, record in enumerate(records) if not isinstance(record, dict) or not record.get("id")]
    if bad:
        fail([f"source inventory records without ids at indexes: {bad}"])
    return records


def appendix_ids(path: Path) -> set[str]:
    return set(ROW_ID_RE.findall(path.read_text(encoding="utf-8", errors="ignore")))


def main() -> None:
    errors: list[str] = []
    records = load_records()
    all_ids = {str(record["id"]) for record in records}
    external_ids = {str(record["id"]) for record in records if record.get("priority") == "external_literature"}
    corpus_ids = all_ids - external_ids

    g_text = APPENDIX_G.read_text(encoding="utf-8", errors="ignore")
    h_text = APPENDIX_H.read_text(encoding="utf-8", errors="ignore")
    g_ids = appendix_ids(APPENDIX_G)
    h_ids = appendix_ids(APPENDIX_H)

    for path, text, title in (
        (APPENDIX_G, g_text, "Corben's Source Corpus"),
        (APPENDIX_H, h_text, "External Literature and References"),
    ):
        if f"# {title}" not in text:
            errors.append(f"{path.relative_to(ROOT)} is missing title {title!r}.")
        if "## Ownership Boundary" not in text:
            errors.append(f"{path.relative_to(ROOT)} is missing the ownership-boundary section.")
        if "Appendix G: Corben's Source Corpus" not in text:
            errors.append(f"{path.relative_to(ROOT)} is missing the Appendix G ownership row.")
        if "Appendix H: External Literature and References" not in text:
            errors.append(f"{path.relative_to(ROOT)} is missing the Appendix H ownership row.")

    unknown_g = g_ids - all_ids
    unknown_h = h_ids - all_ids
    if unknown_g:
        errors.append(f"Appendix G lists unknown source ids: {sorted(unknown_g)}")
    if unknown_h:
        errors.append(f"Appendix H lists unknown source ids: {sorted(unknown_h)}")

    external_in_g = g_ids & external_ids
    corpus_in_h = h_ids & corpus_ids
    missing_from_g = corpus_ids - g_ids
    missing_from_h = external_ids - h_ids
    if external_in_g:
        errors.append(f"Appendix G includes external-literature ids: {sorted(external_in_g)}")
    if corpus_in_h:
        errors.append(f"Appendix H includes Corben/source-corpus ids: {sorted(corpus_in_h)}")
    if missing_from_g:
        errors.append(f"Appendix G is missing source-corpus ids: {sorted(missing_from_g)}")
    if missing_from_h:
        errors.append(f"Appendix H is missing external-literature ids: {sorted(missing_from_h)}")

    if "## Citation Policy" not in g_text:
        errors.append("Appendix G is missing Citation Policy.")
    if "## External Literature Queue" not in h_text:
        errors.append("Appendix H is missing External Literature Queue.")
    if "## External Citation Policy" not in h_text:
        errors.append("Appendix H is missing External Citation Policy.")

    if errors:
        fail(errors)

    print(
        "Source appendix ownership validation passed: "
        f"{len(corpus_ids)} source-corpus records in Appendix G, "
        f"{len(external_ids)} external-literature records in Appendix H."
    )


if __name__ == "__main__":
    main()
