#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json, re, subprocess, sys
from pathlib import Path
from typing import Any
import jsonschema
ROOT=Path(__file__).resolve().parents[1]
LEAN=ROOT/"lean/AsiStackProofs/ResourceEconomicsRefinement.lean";SCHEMA=ROOT/"schemas/resource_economics_refinement.schema.json";RESULT=ROOT/"experiments/resource_economics_refinement/results/2026-07-15-local.json"
COMMAND="python3 scripts/validate_resource_economics_refinement.py"
SOURCES={
"budget":ROOT/"experiments/resource_budget_ledgers/results/2026-07-01-local.md","costed":ROOT/"experiments/costed_route_resource_slice/results/2026-06-29-local.json","workflow":ROOT/"experiments/resource_workflow_trace/results/2026-07-01-local.json","capacity":ROOT/"experiments/capacity_smoothing/results/2026-07-01-local.md","flagship":ROOT/"experiments/resource_flagship_lane/results/2026-07-01-local.json","ci":ROOT/"experiments/resource_ci_cost_profile/results/2026-07-04-main.json","governance":ROOT/"experiments/resource_governance_tax_tradeoff/results/2026-07-03-local.json","simulation":ROOT/"experiments/simulation_transfer_boundaries/results/2026-06-30-local.md","theseus_sim":ROOT/"experiments/theseus_simulation_fidelity_receipt_suite_import/results/2026-07-05-local.json","theseus_export":ROOT/"experiments/theseus_rlds_minari_trace_export_import/results/2026-07-05-local.json","workload":ROOT/"experiments/resource_workload_quality_probe/results/2026-07-01-local.json","load":ROOT/"experiments/resource_load_stability_probe/results/2026-07-01-local.json"}
KINDS={"requested":"bindRequest","budgeted":"declareBudget","reserved":"reserveCapacity","scheduled":"scheduleWork","executed":"recordExecution","verified":"verifyOutcome","transferred":"transportClaim","reconciled":"reconcileSpend","closed":"close"}
ACCEPTED={"acceptBudgeting","acceptReservation","acceptSchedule","acceptExecution","acceptVerification","acceptTransfer","acceptReconciliation","acceptClosure","acceptClosed"}
def load(p:Path)->Any:return json.loads(p.read_text())
def rel(p:Path)->str:return str(p.relative_to(ROOT))
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def run(cmd:list[str],cwd:Path=ROOT)->dict[str,Any]:
 p=subprocess.run(cmd,cwd=cwd,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
 if p.returncode:raise RuntimeError(p.stdout)
 return {"command":" ".join(cmd),"exit_code":0,"output_sha256":hashlib.sha256(p.stdout.encode()).hexdigest()}
def packet()->dict[str,Any]:
 p={"requestDigest":6001,"consumerDigest":6002,"taskDigest":6003,"policyDigest":6004,"rightsDigest":6005,"resourceDigest":6006,"evaluatorDigest":6007,"simulationDigest":6008,"resultDigest":6009,"eventDigest":111,"claimedSupportLevel":1,"fidelitySupportLevel":1}
 for k in ["consumer","task","risk","rights","horizon","nonClaims","resourceInventory","units","directCost","displacedCost","verificationCost","uncertainty","protectedFloors","capacity","reviewerCapacity","verifierCapacity","protectedOverhead","debtExpiry","capacityOwner","queuePolicy","highRiskPriority","tailPolicy","tenantIsolation","fallback","actualSpend","failureRetention","unsafeReleaseAccounting","usefulOutcome","resourceBill","verifierOutcome","evaluatorBoundary","falseDecisionAccounting","residuals","recovery","simulationScope","simulationFidelity","temporalSemantics","simulationResourceBill","simulationOmissions","transferDecision","variance","opportunityCost","incidents","descendants","evidenceTransition","acknowledgment","resultDigestBound","cleanup"]:p[k]=True
 for k in ["rawProxyPromotion","simulated","supportPromotionRequested","externalEffectRequested"]:p[k]=False
 return p
def state(stage,last=0):
 p=packet();return {k:p[k] for k in ["requestDigest","consumerDigest","taskDigest","policyDigest","rightsDigest","resourceDigest","evaluatorDigest","simulationDigest","resultDigest"]}|{"lastEventDigest":last}
def route(stage,kind,p,s):
 if kind!=KINDS[stage]:return "rejectWrongStage"
 if any(p[k]!=s[k] for k in ["requestDigest","consumerDigest","taskDigest"]):return "rejectRequestSubstitution"
 if any(p[k]!=s[k] for k in ["policyDigest","rightsDigest"]):return "rejectPolicySubstitution"
 if p["resourceDigest"]!=s["resourceDigest"]:return "rejectResourceSubstitution"
 if any(p[k]!=s[k] for k in ["evaluatorDigest","simulationDigest","resultDigest"]):return "rejectEvidenceSubstitution"
 if p["eventDigest"]==s["lastEventDigest"]:return "rejectEventReplay"
 if p["supportPromotionRequested"] or p["externalEffectRequested"]:return "rejectAuthorityLeak"
 simple={"requested":[("consumer","requestConsumer"),("task","requestTask"),("risk","requestRisk"),("rights","requestRights"),("horizon","requestHorizon"),("nonClaims","requestNonClaims")],"budgeted":[("resourceInventory","requestResourceInventory"),("units","requestUnits"),("directCost","requestDirectCost"),("displacedCost","requestDisplacedCost"),("verificationCost","requestVerificationCost"),("uncertainty","requestUncertainty"),("protectedFloors","requestProtectedFloors")],"reserved":[("capacity","requestCapacity"),("reviewerCapacity","requestReviewerCapacity"),("verifierCapacity","requestVerifierCapacity"),("protectedOverhead","requestProtectedOverhead"),("debtExpiry","requestDebtExpiry"),("capacityOwner","requestCapacityOwner")],"scheduled":[("queuePolicy","requestQueuePolicy"),("highRiskPriority","requestHighRiskPriority"),("tailPolicy","requestTailPolicy"),("tenantIsolation","requestTenantIsolation"),("fallback","requestFallback")],"executed":[("actualSpend","requestActualSpend"),("failureRetention","requestFailureRetention"),("unsafeReleaseAccounting","requestUnsafeReleaseAccounting"),("usefulOutcome","requestUsefulOutcome"),("resourceBill","requestResourceBill")],"verified":[("verifierOutcome","requestVerifierOutcome"),("evaluatorBoundary","requestEvaluatorBoundary"),("falseDecisionAccounting","requestFalseDecisionAccounting"),("residuals","requestResiduals"),("recovery","requestRecovery")],"reconciled":[("variance","requestVariance"),("opportunityCost","requestOpportunityCost"),("incidents","requestIncidents"),("descendants","requestDescendants"),("evidenceTransition","requestEvidenceTransition")],"closed":[("acknowledgment","requestAcknowledgment"),("resultDigestBound","requestResultDigest"),("cleanup","requestCleanup")]}
 accepts={"requested":"acceptBudgeting","budgeted":"acceptReservation","reserved":"acceptSchedule","scheduled":"acceptExecution","executed":"acceptVerification","verified":"acceptTransfer","reconciled":"acceptClosure","closed":"acceptClosed"}
 if stage in simple:
  for f,o in simple[stage]:
   if not p[f]:return o
  if stage=="executed" and p["rawProxyPromotion"]:return "blockRawProxyPromotion"
  return accepts[stage]
 if stage=="transferred":
  if p["simulated"]:
   for f,o in [("simulationScope","requestSimulationScope"),("simulationFidelity","requestSimulationFidelity"),("temporalSemantics","requestTemporalSemantics"),("simulationResourceBill","requestSimulationResourceBill"),("simulationOmissions","requestSimulationOmissions"),("transferDecision","requestTransferDecision")]:
    if not p[f]:return o
   if p["fidelitySupportLevel"]<p["claimedSupportLevel"]:return "blockFidelityOverclaim"
  return "acceptReconciliation"
 raise AssertionError(stage)
def cases():
 rows=[]
 def add(cid,stage,expected,mutation=None,kind=None,last=0):
  p=packet();p.update(mutation or {});actual=route(stage,kind or KINDS[stage],p,state(stage,last));rows.append({"case_id":cid,"stage":stage,"expected_route":expected,"actual_route":actual,"accepted":actual in ACCEPTED})
 add("wrong-stage","requested","rejectWrongStage",kind="declareBudget")
 for cid,key,out in [("request-substitution","requestDigest","rejectRequestSubstitution"),("policy-substitution","policyDigest","rejectPolicySubstitution"),("resource-substitution","resourceDigest","rejectResourceSubstitution"),("evidence-substitution","evaluatorDigest","rejectEvidenceSubstitution")]:add(cid,"requested",out,{key:999})
 add("event-replay","requested","rejectEventReplay",last=111);add("authority-leak","requested","rejectAuthorityLeak",{"supportPromotionRequested":True})
 simple={"requested":[("consumer","requestConsumer"),("task","requestTask"),("risk","requestRisk"),("rights","requestRights"),("horizon","requestHorizon"),("nonClaims","requestNonClaims")],"budgeted":[("resourceInventory","requestResourceInventory"),("units","requestUnits"),("directCost","requestDirectCost"),("displacedCost","requestDisplacedCost"),("verificationCost","requestVerificationCost"),("uncertainty","requestUncertainty"),("protectedFloors","requestProtectedFloors")],"reserved":[("capacity","requestCapacity"),("reviewerCapacity","requestReviewerCapacity"),("verifierCapacity","requestVerifierCapacity"),("protectedOverhead","requestProtectedOverhead"),("debtExpiry","requestDebtExpiry"),("capacityOwner","requestCapacityOwner")],"scheduled":[("queuePolicy","requestQueuePolicy"),("highRiskPriority","requestHighRiskPriority"),("tailPolicy","requestTailPolicy"),("tenantIsolation","requestTenantIsolation"),("fallback","requestFallback")],"executed":[("actualSpend","requestActualSpend"),("failureRetention","requestFailureRetention"),("unsafeReleaseAccounting","requestUnsafeReleaseAccounting"),("usefulOutcome","requestUsefulOutcome"),("resourceBill","requestResourceBill")],"verified":[("verifierOutcome","requestVerifierOutcome"),("evaluatorBoundary","requestEvaluatorBoundary"),("falseDecisionAccounting","requestFalseDecisionAccounting"),("residuals","requestResiduals"),("recovery","requestRecovery")],"reconciled":[("variance","requestVariance"),("opportunityCost","requestOpportunityCost"),("incidents","requestIncidents"),("descendants","requestDescendants"),("evidenceTransition","requestEvidenceTransition")],"closed":[("acknowledgment","requestAcknowledgment"),("resultDigestBound","requestResultDigest"),("cleanup","requestCleanup")]}
 accepts={"requested":"acceptBudgeting","budgeted":"acceptReservation","reserved":"acceptSchedule","scheduled":"acceptExecution","executed":"acceptVerification","verified":"acceptTransfer","reconciled":"acceptClosure","closed":"acceptClosed"}
 for stage,pairs in simple.items():
  for f,o in pairs:add(f"{stage}-{f}",stage,o,{f:False})
  if stage=="executed":add("executed-raw-proxy",stage,"blockRawProxyPromotion",{"rawProxyPromotion":True})
  add(f"{stage}-accepted",stage,accepts[stage])
 for f,o in [("simulationScope","requestSimulationScope"),("simulationFidelity","requestSimulationFidelity"),("temporalSemantics","requestTemporalSemantics"),("simulationResourceBill","requestSimulationResourceBill"),("simulationOmissions","requestSimulationOmissions"),("transferDecision","requestTransferDecision")]:add(f"transferred-{f}","transferred",o,{"simulated":True,f:False})
 add("transferred-overclaim","transferred","blockFidelityOverclaim",{"simulated":True,"claimedSupportLevel":2,"fidelitySupportLevel":1});add("transferred-accepted","transferred","acceptReconciliation",{"simulated":True})
 return rows
def source_results(errors):
 c=load(SOURCES["costed"]);w=load(SOURCES["workflow"]);f=load(SOURCES["flagship"]);ci=load(SOURCES["ci"]);g=load(SOURCES["governance"]);ts=load(SOURCES["theseus_sim"]);te=load(SOURCES["theseus_export"]);wl=load(SOURCES["workload"]);ld=load(SOURCES["load"])
 counts={"budget_valid_count":len(list((ROOT/"experiments/resource_budget_ledgers/fixtures").glob("valid_*.json"))),"budget_invalid_count":len(list((ROOT/"experiments/resource_budget_ledgers/fixtures").glob("invalid_*.json"))),"costed_eligible_count":len(c["eligible_routes"]),"costed_rejected_count":len(c["rejected_routes"]),"workflow_valid_count":w["valid_fixture_count"],"workflow_invalid_count":w["expected_invalid_fixture_count"],"workflow_step_count":w["step_count"],"capacity_valid_count":len(list((ROOT/"experiments/capacity_smoothing/fixtures").glob("valid_*.json"))),"capacity_invalid_count":len(list((ROOT/"experiments/capacity_smoothing/fixtures").glob("invalid_*.json"))),"flagship_command_count":len(f["command_records"]),"flagship_artifact_count":len(f["tracked_artifacts"]),"ci_run_count":len(ci["runs"]),"ci_failure_count":len(ci["failure_events"]),"governance_valid_count":g["valid_scenario_count"],"governance_invalid_count":g["expected_invalid_control_count"],"governed_selection_count":sum(x["selected_route"]=="governed" for x in g["scenario_results"] if x["actual_valid"]),"low_risk_shortcut_count":sum(x["selected_route"]=="ungoverned_shortcut" for x in g["scenario_results"] if x["actual_valid"]),"simulation_valid_count":len(list((ROOT/"experiments/simulation_transfer_boundaries/fixtures").glob("valid_*.json"))),"simulation_invalid_count":len(list((ROOT/"experiments/simulation_transfer_boundaries/fixtures").glob("invalid_*.json"))),"theseus_sim_scenario_count":ts["fixture_scenario_count"],"theseus_sim_receipt_count":ts["world_adapter_receipt_count"],"theseus_sim_invalid_count":ts["expected_invalid_count"],"theseus_export_ready_count":te["ready_count"],"theseus_export_format_count":te["format_count"],"theseus_export_field_count":te["field_count"],"theseus_export_invalid_count":te["expected_invalid_control_count"],"workload_probe_pass_count":int(wl["pass"]),"load_probe_pass_count":int(ld["pass"])}
 expected={"budget_valid_count":6,"budget_invalid_count":7,"costed_eligible_count":2,"costed_rejected_count":2,"workflow_valid_count":1,"workflow_invalid_count":5,"workflow_step_count":3,"capacity_valid_count":3,"capacity_invalid_count":6,"flagship_command_count":10,"flagship_artifact_count":26,"ci_run_count":8,"ci_failure_count":3,"governance_valid_count":3,"governance_invalid_count":5,"governed_selection_count":2,"low_risk_shortcut_count":1,"simulation_valid_count":3,"simulation_invalid_count":6,"theseus_sim_scenario_count":5,"theseus_sim_receipt_count":6,"theseus_sim_invalid_count":7,"theseus_export_ready_count":1,"theseus_export_format_count":3,"theseus_export_field_count":7,"theseus_export_invalid_count":7,"workload_probe_pass_count":1,"load_probe_pass_count":1}
 if counts!=expected:errors.append(f"source counts drifted: {counts}")
 validators=["validate_resource_budget_ledgers.py","validate_costed_route_resource_slice.py","validate_resource_workflow_trace.py","validate_capacity_smoothing.py","validate_resource_flagship_lane.py","validate_resource_ci_cost_profile.py","validate_resource_governance_tax_tradeoff.py","validate_simulation_transfer_boundaries.py","validate_theseus_simulation_fidelity_receipt_suite_import.py","validate_theseus_rlds_minari_trace_export_import.py","validate_resource_workload_quality_probe.py","validate_resource_load_stability_probe.py"]
 return {"counts":counts,"sha256":{rel(p):sha(p) for p in SOURCES.values()},"validator_runs":[run(["python3",f"scripts/{v}"]) for v in validators]}
def build(errors):
 rows=cases();text=LEAN.read_text();body=re.search(r"inductive Route where(?P<body>.*?)deriving DecidableEq",text,re.S).group("body");declared=set(re.findall(r"\|\s+([A-Za-z][A-Za-z0-9]*)",body));reached={x["actual_route"] for x in rows};negative=[x for x in rows if not x["accepted"]]
 for x in rows:
  if x["actual_route"]!=x["expected_route"]:errors.append(f"{x['case_id']}: {x['actual_route']} != {x['expected_route']}")
 if (len(declared),len(reached),len(rows),len(negative))!=(66,66,66,57):errors.append(f"route coverage drifted: {len(declared)}/{len(reached)}/{len(rows)}/{len(negative)}")
 return {"schema_version":"asi_stack.resource_economics_refinement.result.v1","result_id":"2026-07-15-resource-economics-refinement","recorded_date":"2026-07-15","command":COMMAND,"model":{"lean_module":rel(LEAN),"stage_count":9,"route_count":len(declared),"reached_route_count":len(reached),"route_case_count":len(rows),"rejected_mutation_count":len(negative),"simulation_transfer_route_reached":"acceptReconciliation" in reached,"closed_route_reached":"acceptClosed" in reached,"support_assignment_count":0,"external_effect_count":0},"source_result_refinement":source_results(errors),"route_cases":rows,"lean_verification":run(["lake","env","lean","AsiStackProofs/ResourceEconomicsRefinement.lean"],ROOT/"lean"),"support_state_effect":"none","external_effect":"none","residuals":["Finite authored allocation-and-claim-transport lifecycle only; no deployed scheduler, market, serving system, reviewer pool, or simulator ran.","Source suites combine synthetic fixtures, repository replays, local timing, historical CI records, and sanitized imports with different evidence meanings.","The costed-route 66.98% result and governance-pays scenarios are fixture-specific and do not establish economic optimality or general savings.","Simulation scope, fidelity, temporal semantics, omissions, resource bills, and support levels are authored gates or bounded records, not calibrated world-model measurements."],"non_claims":["no economic optimality, useful-throughput, model quality, safety, deployed scheduling, simulation adequacy, physical feasibility, transfer, SOTA, AGI, ASI, or support claim","no inference from cost arithmetic, repository replay, CI timing, route coverage, or green validators to real-world resource benefit","no support assignment or external effect"]}
def main():
 a=argparse.ArgumentParser();a.add_argument("--write-result",action="store_true");args=a.parse_args();errors=[];result=build(errors);jsonschema.validate(result,load(SCHEMA));serialized=json.dumps(result,indent=2)+"\n"
 if args.write_result:RESULT.parent.mkdir(parents=True,exist_ok=True);RESULT.write_text(serialized)
 elif not RESULT.exists() or RESULT.read_text()!=serialized:errors.append(f"{rel(RESULT)} stale; run {COMMAND} --write-result")
 if errors:print("Resource Economics refinement failed:\n - "+"\n - ".join(errors));sys.exit(1)
 print("Resource Economics refinement passed: 9 stages, 66 routes, 57/57 mutations rejected; twelve bounded resource/simulation results digest-bound; support/effect none.")
if __name__=="__main__":main()
