#!/usr/bin/env python3
"""Validate the generated source-ownership appendices.

Appendix G is reserved for Corben-authored, Corben-supplied, and local project sources.
Appendix H is reserved for third-party external sources by other authors.
The split is generated by `scripts/sync_scaffold.py` from
`sources/source_inventory.json`; this guard makes that ownership boundary
explicit in CI.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ROOT / "sources" / "source_inventory.json"
APPENDIX_G = ROOT / "appendices" / "G_corben_source_corpus.qmd"
APPENDIX_H = ROOT / "appendices" / "H_external_sources.qmd"
ROW_ID_RE = re.compile(r"^\|\s*`([^`]+)`\s*\|", re.MULTILINE)
APPENDIX_G_TITLE = "Corben-Authored, Supplied, and Local Sources"
APPENDIX_H_TITLE = "External Sources by Other Authors"
APPENDIX_G_IDENTITY = "| Appendix identity | Appendix G: Corben-authored, Corben-supplied, and local project sources |"
APPENDIX_H_IDENTITY = "| Appendix identity | Appendix H: external sources by other authors |"
APPENDIX_G_OWNERSHIP_RULE = "| Ownership rule | If Corben wrote it, supplied it, recovered it from his project history, or built it in a local project, it belongs here; if another author, organization, or outside project produced it, it belongs in Appendix H. |"
APPENDIX_H_OWNERSHIP_RULE = "| Ownership rule | If another author, organization, or outside project produced it, it belongs here; Corben-authored papers, Corben-supplied materials, recovered project history, and local-project records stay in Appendix G. |"
APPENDIX_G_BOUNDARY = 'not a combined "sources used" appendix'
APPENDIX_H_BOUNDARY = "not a subsection, second half, or continuation of Appendix G"
OWNERSHIP_GLANCE_SECTION = "## Ownership At A Glance"
OWNERSHIP_GLANCE_G_ROW = "| Corben-authored, Corben-supplied, recovered, or local project material | Appendix G |"
OWNERSHIP_GLANCE_H_ROW = "| Third-party papers, documentation, outside projects, or non-Corben references | Appendix H |"


def fail(errors: list[str]) -> None:
    print("Source appendix ownership validation failed:")
    for error in errors:
        print(f" - {error}")
    sys.exit(1)


def load_records() -> list[dict]:
    records = json.loads(INVENTORY.read_text(encoding="utf-8"))
    if not isinstance(records, list):
        fail(["sources/source_inventory.json must contain a list."])
    bad = [index for index, record in enumerate(records) if not isinstance(record, dict) or not record.get("id")]
    if bad:
        fail([f"source inventory records without ids at indexes: {bad}"])
    return records


def appendix_ids(path: Path) -> set[str]:
    return set(ROW_ID_RE.findall(path.read_text(encoding="utf-8", errors="ignore")))


def main() -> None:
    errors: list[str] = []
    records = load_records()
    all_ids = {str(record["id"]) for record in records}
    external_ids = {str(record["id"]) for record in records if record.get("priority") == "external_literature"}
    corpus_ids = all_ids - external_ids

    g_text = APPENDIX_G.read_text(encoding="utf-8", errors="ignore")
    h_text = APPENDIX_H.read_text(encoding="utf-8", errors="ignore")
    g_ids = appendix_ids(APPENDIX_G)
    h_ids = appendix_ids(APPENDIX_H)

    for path, text, title in (
        (APPENDIX_G, g_text, APPENDIX_G_TITLE),
        (APPENDIX_H, h_text, APPENDIX_H_TITLE),
    ):
        if f"# {title}" not in text:
            errors.append(f"{path.relative_to(ROOT)} is missing title {title!r}.")
        if "## Appendix Scope" not in text:
            errors.append(f"{path.relative_to(ROOT)} is missing the appendix-scope section.")

    if APPENDIX_G_BOUNDARY not in g_text:
        errors.append("Appendix G is missing the explicit non-combined source boundary.")
    if APPENDIX_H_BOUNDARY not in h_text:
        errors.append("Appendix H is missing the explicit separate-appendix boundary.")
    if APPENDIX_G_IDENTITY not in g_text:
        errors.append("Appendix G is missing its standalone Appendix G identity row.")
    if APPENDIX_H_IDENTITY not in h_text:
        errors.append("Appendix H is missing its standalone Appendix H identity row.")
    if APPENDIX_G_OWNERSHIP_RULE not in g_text:
        errors.append("Appendix G is missing the Corben-side ownership rule row.")
    if APPENDIX_H_OWNERSHIP_RULE not in h_text:
        errors.append("Appendix H is missing the external-source ownership rule row.")
    for appendix_name, text in (("Appendix G", g_text), ("Appendix H", h_text)):
        if OWNERSHIP_GLANCE_SECTION not in text:
            errors.append(f"{appendix_name} is missing the Ownership At A Glance section.")
        if OWNERSHIP_GLANCE_G_ROW not in text:
            errors.append(f"{appendix_name} is missing the Appendix G ownership-at-a-glance row.")
        if OWNERSHIP_GLANCE_H_ROW not in text:
            errors.append(f"{appendix_name} is missing the Appendix H ownership-at-a-glance row.")
    if APPENDIX_H_IDENTITY in g_text:
        errors.append("Appendix G should not render Appendix H as a second scope row.")
    if APPENDIX_G_IDENTITY in h_text:
        errors.append("Appendix H should not render Appendix G as a second scope row.")

    unknown_g = g_ids - all_ids
    unknown_h = h_ids - all_ids
    if unknown_g:
        errors.append(f"Appendix G lists unknown source ids: {sorted(unknown_g)}")
    if unknown_h:
        errors.append(f"Appendix H lists unknown source ids: {sorted(unknown_h)}")

    external_in_g = g_ids & external_ids
    corpus_in_h = h_ids & corpus_ids
    missing_from_g = corpus_ids - g_ids
    missing_from_h = external_ids - h_ids
    if external_in_g:
        errors.append(f"Appendix G includes external-literature ids: {sorted(external_in_g)}")
    if corpus_in_h:
        errors.append(f"Appendix H includes Corben-authored, Corben-supplied, or local project source ids: {sorted(corpus_in_h)}")
    if missing_from_g:
        errors.append(f"Appendix G is missing Corben-authored, Corben-supplied, or local project source ids: {sorted(missing_from_g)}")
    if missing_from_h:
        errors.append(f"Appendix H is missing external-literature ids: {sorted(missing_from_h)}")

    if "## Citation Policy" not in g_text:
        errors.append("Appendix G is missing Citation Policy.")
    if "## External Literature Queue" not in h_text:
        errors.append("Appendix H is missing External Literature Queue.")
    if "## External Citation Policy" not in h_text:
        errors.append("Appendix H is missing External Citation Policy.")

    if errors:
        fail(errors)

    print(
        "Source appendix ownership validation passed: "
        f"{len(corpus_ids)} Corben-authored, Corben-supplied, or local project source records in Appendix G, "
        f"{len(external_ids)} external-literature records by other authors in Appendix H."
    )


if __name__ == "__main__":
    main()
